### ISSUE TITLE
involucre

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#100]
This term should be a child of collective phyllome structure.
Current def'n: A whorl of bracts at the base of a cluster of flowers as found in Asteraceae or Compositae. 

This def'n needs to be worked on.

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/100](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/100)

**Comment by cooperl09** [comment]
Revised def'n of involucral bract (PO:0009045):
Current Definition:  Equals inflorescence bract of an involucre, as in Asteraceae or Compositeae.    
Revised def’n: An inflorescence bract (PO:0009054) of an involucre (PO:0009100).    

New comment: Involucre are found in the plant families such as Asteraceae or Compositeae.
