### ISSUE TITLE
portion of ground tissue

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#106]
Changed term [PO:0000500](http://purl.obolibrary.org/obo/PO_0000500) 'ground tissue' to 'portion of ground tissue.' 

Has no definition.

The most common definition out there is: Any portion of plant tissue other than the dermal or vascular tissue. 
Develops from the ground meristem (meristem L2 and meristem L3).

I know this is defining by what it's not. I'll try to find a better one.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/106](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/106)

**Comment by DarioJCavaliere** [comment]
@cooperl09 Should we close this? This issue looks resolved.
