### ISSUE TITLE
tuber and shoot axis tuber

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#127]
Right now, tuber is_a shoot. Should probably be is_a stem, but this will depend on how we define shoot and stem.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/127](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/127)

**Comment by cooperl09** [comment]
Revised hierarchy for tubers:
Was: 
shoot axis tuber (PO:0004543): A tuber (PO:0025522) that develops from a branch (PO:0025073).
Revised:
shoot axis tuber (PO:0004543): A shoot axis (PO:0025029) that develops from a branch (PO:0025073) and is radially enlarged for storage.
- Maintained the other is_a parent link to tuber for now.
