### ISSUE TITLE
shoot axis node and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#145]
I suggest renaming the term shoot node ([PO:0005004](http://purl.obolibrary.org/obo/PO_0005004)) to node, since all nodes occur on shoots, and it is redundant and too easily confused with stem node.

Proposed def: A region of a shoot system that is part of a shoot axis where a spikelet, flower, floret, branch, bud and/or leaves are attached.
Part_of shoot axis instead of shoot system. 

Should be is_a cardinal organ part (since it is part of shoot axis).

Children:
-inflorescence node ([PO:0006325](http://purl.obolibrary.org/obo/PO_0006325)): A node that is part of an inflorescence axis and where a spikelet, flower, floret or inflorescence branch is attached. (EXISTING TERM)
-stem node ([PO:0020141](http://purl.obolibrary.org/obo/PO_0020141)): A node that is part of a stem. (EXISTING TERM)
-branch node ([PO:0025024](http://purl.obolibrary.org/obo/PO_0025024)): A node that is part of a branch. (NEW TERM)

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/145](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/145)

**Comment by cooperl09** [comment]
stem node (PO:0020141)-  slight revision of def'n.
def'n: A shoot node that is part of a stem.
Revised def'n:  A shoot axis node (PO:0005004) that is part of a stem (PO:0009047).

**Comment by cooperl09** [comment]
inflorescence node (PO:0006325)
Revised label: inflorescence axis node (PO:0006325)
Current def'n:  A shoot node that is part of an inflorescence axis and where a spikelet, flower, floret or inflorescence branch is attached.
Revised def'n:  A shoot axis node (PO:0005004) that is part of an inflorescence axis (PO:0020122).

**Comment by cooperl09** [comment]
cotyledonary node (PO:0025321): 
Current def'n: A stem node from which one or more cotyledons grow.
Revised def'n:  A stem node (PO:0020141) from which cotyledons (PO:0020030) may develop.

**Comment by cooperl09** [comment]
scutellar node  PO:0004708
Current def'n:  A stem node that is the part of an embryo axis directly above the radicle where the scutellum is attached.

Revised def'n:  A stem node (PO:0020141) that is part of a plant embryo axis (PO:0019018), 
where the scutellum (PO:0020110) is attached.
I left off the phrase about the proximity to the radicle to avoid confusion.
