### ISSUE TITLE
shoot-borne root (PO:0000042) and shoot-borne root meristem (PO:0006021)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#163]
Rich Zobel of the ISRR (International Society for Root Research) has suggested the a modification of the term 'shoot borne root' based on the root nomenclature framework they developed and published in Plant Biosystems (June 2010). See tracker: https://sourceforge.net/tracker/?func=detail&aid=2899934&group\_id=76834&atid=835555.

Current def'n: Post-embryonic root developed from shoot tissue, with synonyms ('related'): adventitious root and stilt root

comments fro RZ: Name should be changed to insert a hyphen (shoot-borne). 
The synonym adventitious is too broad. In common use, it encompasses three primary classes of root (lateral roots that are not from the pericycle; basal roots, and shoot-borne roots).
synonym: "adventitious root" BROAD 
synonym: "aerial root" NARROW 
synonym: "stilt root" NARROW 
is_a: [PO:0009005](http://purl.obolibrary.org/obo/PO_0009005) ! root
relationship: develops_from [PO:0009006](http://purl.obolibrary.org/obo/PO_0009006) (shoot system)

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/163](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/163)

**Comment by cooperl09** [comment]
prop root (PO:0000044):
Revised def'n:  A shoot-borne nodal root (PO:0003005) formed at a stem node (PO:0020141) above the ground and growing directly into the soil.
Revised comment:
This term is perhaps best defined functionally to prop the plant up, but sometimes prop roots may also act as breathing roots. Compare to pneumatophore (PO:0025357), which is a lateral root that grows upwards from below the soil or water surface.
