### ISSUE TITLE
strobilus and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#168]
We have been using the term strobilus bud, so we should probably have the term strobilus as well.

Proposed definition (from Raven et al.): A reproductive shoot system consisting of a number of modified leaves (sporophylls) or ovule-bearing scales grouped terminally on a stem.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/168](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/168)

**Comment by cooperl09** [comment]
Now that we have megasporangiate strobilus (PO:0005032) and microsporangiate strobilus (PO:0005031), please move the synonyms to the more specific terms, along with their xrefs.

**Comment by cooperl09** [comment]
strobilus (PO:0025083): 
Current def'n: A reproductive shoot system consisting of a number of modified leaves (sporophylls) or ovule-bearing scales grouped terminally on a stem.

Revised def'n: 
strobilus (PO:0025083): A reproductive shoot system (PO:0025082) consisting of a number of sporophylls (PO:0009026) or plant ovule (PO:0020003)-bearing modified leaves (PO:0025034) grouped terminally on a stem (PO:0009047).

current Synonyms:
related: female cone
related: macrostrobili (FNA:ff4b92f1-d0aa-4d75-89ba-934aa07fba2d)
related: macrostrobilus (FNA:ed33e80e-12e2-41a3-8a0d-655a842189a6)
related: male cone
related: megastrobili (FNA:a116a573-2ca8-4bda-b3e7-d0d89e6e2107)
related: megastrobilus (FNA:a116a573-2ca8-4bda-b3e7-d0d89e6e2107)
narrow: microstrobilus
narrow: ovulate cone
narrow: pollen cone
exact: cono (Spanish); Japanese 
exact: strobili (plural)

Revised Synonyms:
narrow: simple strobilus
narrow: compound strobilus
related: cone
exact: cono (Spanish); Japanese 
exact: strobili (plural)

Added missing Xref to PO_GIT:168

**Comment by cooperl09** [comment]
megasporangiate strobilus (PO:0005032): 
slightly revised def'n: 
A strobilus (PO:0025083) that bears only plant ovules (PO:0020003).

Synonyms:
related: female cone
narrow: ovulate cone
related: megastrobilus (FNA:a116a573-2ca8-4bda-b3e7-d0d89e6e2107)
related (pl): megastrobili (FNA:a116a573-2ca8-4bda-b3e7-d0d89e6e2107)

related (pl): macrostrobili (FNA:ff4b92f1-d0aa-4d75-89ba-934aa07fba2d)
related: macrostrobilus (FNA:ed33e80e-12e2-41a3-8a0d-655a842189a6)


slightly revised def'n:
microsporangiate strobilus (PO:0005031):
A strobilus (PO:0025083) that bears only pollen (PO:0025281).

related: male cone
related: pollen cone
related: microstrobilus (FNA:ebda7bb0-bb12-4160-bbc6-a5edc4fb316c)

related (pl): microstrobili

See also term request: hop cone #601
