### ISSUE TITLE
internode root 

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#170]
Rich Zobel of the ISRR \(International Society for Root Research\) has suggested the new term 'internode root ' based on the root nomenclature framework they developed and published in Plant Biosystems \(June 2010\). 

See tracker: [plant-ontology-po-term-requests:#48]
See tracker: [plant-ontology-po-term-requests:#170]

internode root  \([ID:0000005](http://purl.obolibrary.org/obo/ID_0000005)\)
proposed def: "Shoot-borne roots that arise from non-shoot-node tissues." \[ISS:RWZ\]
comment: The synonym adventitious is too broad. In common use, it encompasses three primary classes of root \(lateral roots that are not from the pericycle; basal root, and shoot-borne root\).
synonym: "adventitious root" BROAD 
is\_a: [PO:0000042](http://purl.obolibrary.org/obo/PO_0000042) \! shoot-borne root

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/170](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/170)

**Comment by cooperl09** [comment]
Resolved
