### ISSUE TITLE
plant axis elongation zone (PO:0025180) and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#197]
The term elongation zone ([PO:0020125](http://purl.obolibrary.org/obo/PO_0020125)) currently has no is_a parent.
Current definiton: The portion of the root that includes small, densely cytoplasmic cells that are dividing and expanding in size. [GR:pj]
synonym  "region of cell elongation" RELATED []:
synonym  "region of radial enlargement" RELATED []:
part_of root

Comment from DWS: Zone of elongation in roots at least refers to longitudinal expansion not radial. The new definition will not work. Also, those cells have enlarging vacuoles so the cytoplasm actually becomes less dense. 

The elongation zone is the part of the root directly behind the root apical meristem, in which cells are expanding longitudinally. Since vascular tissue is beginning to differentiate in this part of the root, it is not composed of one type of tissue. Suggest making it is_a cardinal organ part.

Proposed definition (based on description in Raven et al.): A cardinal organ part that is part of a root that is located directly behind a root apical meristem, in which the cells are undergoing longitudinal expansion.
Comment: The elongation zone is only a few millimeters in length and is the only portion of the root in which cell elongation generally occurs. Root hairs are not yet produced in this region.
Synonym: region of cell elongation (Raven et al's name) 
is_a cardinal organ part, part_of root

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/197](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/197)

**Comment by cooperl09** [comment]
plant axis elongation zone (PO:0025180):
Was: A cardinal organ part that is part of a plant axis that is located directly behind an apical meristem, in which the cells are undergoing longitudinal expansion.

Revised def'n: A cardinal organ part (PO:0025001) which is part of a plant axis (PO:0025004), is located proximal to an apical meristem (PO:0020144), and in which plant cells (PO:0009002) are undergoing longitudinal expansion.

Added missing Xref to PO_GIT:197

**Comment by cooperl09** [comment]
shoot internode elongation zone (PO:0025100) :
Revised name -->  shoot axis internode elongation zone (PO:0025100)

Was: A plant axis elongation zone that is part of a shoot axis internode.

Revised def'n: A plant axis elongation zone (PO:0025180) that is part of a shoot axis internode (PO:0005005).

Added missing Xref to PO_GIT:197

**Comment by cooperl09** [comment]
stem internode elongation zone  (PO:0008041)
Was: A shoot internode elongation zone that is part of a stem internode.

Revised def'n:A shoot axis internode elongation zone  (PO:0025100) that is part of a stem internode (PO:0009047).

Added missing Xref to PO_GIT:197

**Comment by cooperl09** [comment]
branch internode elongation zone (PO:0025101):
A shoot axis internode elongation zone that is part of a branch internode.

Revised def'n: A shoot axis internode elongation zone (PO:0025100) that is part of a branch internode (PO:0025080).

Added missing Xref to PO_GIT:197

**Comment by cooperl09** [comment]
root elongation zone (PO:0025181):
was: A plant axis elongation zone that is part of a root tip and located directly behind the root apical meristem.

Revised def'n:  A plant axis elongation zone (PO:0025180) that is part of a root tip (PO:0000025) and located proximal to a root apical meristem (PO:0020147).

Added missing Xref to PO_GIT:197

**Comment by cooperl09** [comment]
primary root elongation zone (PO:0025257): 
was: A root elongation zone that is part of a primary root tip.

Revised def'n: A root elongation zone (PO:0025181) that is part of a primary root tip (PO:0000026).

Added missing Xref to PO_GIT:197
