### ISSUE TITLE
inflorescence and infructescence

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#260]
In order to address new term requests for Musa, we need solid definitions of inflorescence and infructescence that follow the genus/differentia form.

Current definition of inflorescence: That part of the axial system of plants above the uppermost foliage leaf/pair of foliage leaves that bears flowers, is_a reproductive shoot system.

'''Proposed definition of inflorescence:''' a reproductive shoot system that has as parts all of the shoot axes distal to the most distal foliage leaf of a shoot axis and all of the flowers borne by those axes. Must have two or more flowers as parts.

Current definition of infructescence: The grouping or arrangement in which fruits are borne on a plant.

'''Proposed definition of infructescence:''' a reproductive shoot system that develops from an inflorescence and has as parts all of the shoot axes distal to the most distal foliage leaf of a shoot axis and all of the fruits borne by those axes.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/260](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/260)

**Comment by cooperl09** [comment]
inflorescence (PO:0009049)
Current def’n: 
A reproductive shoot system (PO:0025082) that has as parts all of the shoot axes (PO:0025029) distal to the most distal foliage leaf (PO:0009025) of a shoot axis and all of the flowers (PO:0009046) borne by those axes. Must have two or more flowers as parts.   

Revised def’n: 
A reproductive shoot system (PO:0025082) that has as parts all of the shoot axes (PO:0025029) and flowers (PO:0009046; must have two or more) distal to the most distal leaf (PO:0009025).  

Current comment: 
Some plants have only solitary flowers, e.g. Magnolia.

Revised comment: 
Inflorescences are reproductive shoot systems from which at least two flowers develop.
The growth pattern of an Inflorescences may be monopodial (single main shoot axis), or sympodial (growth occurs from axillary meristems).  The axes of an inflorescence can be determinate or indeterminate. Many plants, for example Magnolia, have solitary flowers (PO:0009046).
