### ISSUE TITLE
locule (PO:0025263) and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#271]
The term locule was requested by Austin Mast for legumes. Applies to many other taxa as well.

Locule can be used to refer to the cavity in an carpel or in an anther.  In the PGDSO, we have the term [PO:0001026](http://purl.obolibrary.org/obo/PO_0001026) locules established, which is an anther development stage. This should be renamed anther locules established For clarity, we may want to add two terms: anther locule and carpel locule. Could also add a new general term locule.

anther locule: A plant anatomical space that is a cavity in an anther formed by a single pollen sac.

carpel locule: A plant anatomical space that is a cavity in a carpel that contains at least one ovule. Comment: A syncarpous gynoecium may have multiple locules, and the locules of multiple carpels may be fused.

May want to add general parent terms locule: A plant anatomical space that is a cavity within a sporophyll. Synonym: loculus

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/271](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/271)

**Comment by cooperl09** [comment]
Other locules:
fruit locule (PO:0025270): A locule (PO:0025263) that is a cavity in a fruit (PO:0009001) and develops from a plant ovary locule (PO:0025266).

sporangium locule (PO:0025265):  A locule (PO:0025263) that is a cavity in a sporangium (PO:0025094) or several fused sporangia.
