### ISSUE TITLE
plant ovary (PO:0009072) and its parts

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#280]
Ovary ([PO:0009072](http://purl.obolibrary.org/obo/PO_0009072)) is part of carpel, but should be part_of gynoecium, because it can be part of multiple carpels. Should be is_a plant structure, rather than cardinal organ part, because it can be part of one ovary or more.

Current def. of ovary: The basal portion of a carpel or group of fused carpels, that encloses the ovule(s). [source: APWeb:Glossary, TAIR:lr]

Definition: A plant structure that is the basal portion of a carpel or group of fused carpels and encloses the ovule(s). part_of gynoecium, is_a plant structure 
Comment: May not contain ovules in the case of sterile fruit. 

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/280](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/280)

**Comment by cooperl09** [comment]
Currently:     plant ovary  (PO:0009072)
Def'n A plant structure (PO:0009011) that is the basal portion of a carpel (PO:0009030) or group of fused carpels and encloses the plant ovule(s) (PO:0020003). Source: TAIR:Leonore_Reiser, APweb:Glossary 
Comment: If you are annotating to this structure for Zea mays or other grasses, please also add an annotation to the corresponding floret type. Choose the most specific term possible from: spikelet floret (PO:0009082), ear floret (PO:0006354), upper floret of pedicellate spikelet of ear (PO:0006350), upper floret of sessile spikelet of ear (PO:0006352).

**Comment by cooperl09** [comment]
Renamed parts of plant ovary to include 'plant" as in the parent term:
- **ovary locule (PO:0025266)  >> plant ovary locule (PO:0025266)**
Was: A locule that is a cavity in an ovary.
Revised def'n:  A locule (PO:0025263) that is a cavity in a plant ovary (PO:0009072).

**Comment by cooperl09** [comment]
**ovary wall (PO:0005022) >> plant ovary wall (PO:0005022)**
Was: ovary wall (PO:0005022): A wall of an ovary that is composed of abaxial (outer) and adaxial (inner) epidermis and a middle layer, composed of mesophyll cells and a distinct subepidermal adaxial cell layer (as found in Arabidopsis).

Revised: plant ovary wall (PO:0005022):
A portion of plant tissue (PO:0009007) that is composed of plant ovary abaxial (outer) epidermis (PO:0005023), plant ovary adaxial (inner) epidermis (PO:0005024), and a plant ovary wall middle layer (PO:0005025).

**Comment by cooperl09** [comment]
WAS: abaxial epidermis of ovary (PO:0005023): The epidermal cell layer of the abaxial/outer surface of the ovary.

REVISED: plant ovary abaxial epidermis (PO:0005023): A portion of ovary epidermis (PO:0006063) which is the outer surface of a plant ovary (PO:0009072).


WAS:  adaxial epidermis of ovary  (PO:0005024)
REVISED:  plant ovary adaxial epidermis (PO:0005024): A portion of ovary epidermis (PO:0006063) which is the inner surface of a plant ovary (PO:0009072).


WAS: middle layer of ovary wall (PO:0005025): A portion of tissue that is composed of one or more mesophyll layers. It may have a distinct subepidermal adaxial cell layer (as found in <i>Arabidopsis</i>).
REVISED: plant ovary wall middle layer (PO:0005025): A portion of chlorenchyma tissue (PO:0005426) that is part of the plant ovary wall (PO:0005022) and is composed of mesophyll cells (PO:0004006).

Revised comment: In some species, such as Arabidopsis, there may be a distinct subepidermal adaxial cell layer. The cells in the mesophyll layer(s) may not differentiate similar to the spongy and palisade cells found in the leaf mesophyll.

**Comment by cooperl09** [comment]
A few minor revisions to plant ovary related terms. Added ‘plant’ to names for consistency

Was ovary placenta (PO:0020001):
A portion of placenta tissue that is part of an ovary and to which ovules are attached.

Revised:
plant ovary placenta (PO:0020001):
A portion of placenta tissue (PO:0025078) which is part of a plant ovary (PO:0009072), and to which plant ovary ovules (PO:0025490) are attached.
PO_GIT:144

Was:
ovary replum (PO:0025272)
A portion of ovary placenta tissue that divides an ovary into two or more chambers and develops from contact of the placental tissue from opposite sides of the ovary early in gynoecium development.

Revised:
plant ovary replum (PO:0025272):
A portion of ovary placenta tissue (PO:0020001) that divides a plant ovary (PO:0009072) into two or more chambers, and develops from contact of the placental tissue from opposite sides of the plant ovary early in gynoecium development (GO:0048467).

Was:
ovary septum PO:0025262
Revised:
plant ovary septum PO:0025262:

Was:
ovary epidermis PO:0006063
Revised: plant ovary epidermis PO:0006063
