### ISSUE TITLE
anther and anther theca

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#297]
We have the term '''theca''' ([PO:0009069](http://purl.obolibrary.org/obo/PO_0009069)): A part of the anther consisting of paired sporangia that dehisce down a common slit.

Theca currently is_a pollen sac, but it is really two pollen sacs. Suggest making it a be is_a collective organ part structure.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/297](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/297)

**Comment by cooperl09** [comment]
Updated def'n:
anther (PO:0009066):  A collective plant organ structure (PO:0025007) that is the pollen-bearing part of a stamen (PO:0009029).

collective plant organ structure (PO:0025007):
A collective plant structure (PO:0025497) that is a proper part of a whole plant (PO:0000003), and is composed of two or more adjacent plant organs (PO:0009008) and the associated portions of plant tissue (PO:0009007).
Anthers are composed of one or more pollen sacs PO:0025277
