### ISSUE TITLE
new term for Hull

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#3]
Hi All,

I need a new term to describe 'hull' in cereal plants.
I know experts say that it is nothing different than
lemma and palea, the two parts found in grass floret.
Therefore the options are to put 'hull' as synonyms of
both lemma and palea, which I somehow disagree because
the term 'hull' is never used in florets/grass flowers.
The usage is only in the grass fruits (caryopsis). It
also appears that the same term is used in other
families as well. So we need a species/organ specific
distinction as well.

# dry outer covering of a fruit or seed or nut
# persistent enlarged calyx at base of e.g. a
strawberry or raspberry

-Pankaj

Reported by: jaiswalp

Original Ticket: "obo/plant-ontology-po-term-requests/3":https://sourceforge.net/p/obo/plant-ontology-po-term-requests/3

**Comment by linuxjackto1** [comment]
thanks www.movied.org
