### ISSUE TITLE
venter

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#306]
Suggest we add this term for bryophytes.

proposed def.: A cardinal organ part that is the enlarged basal part of an archegonium and contains an egg cell.

part\_of archegonium

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/306](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/306)

**Comment by cooperl09** [comment]
Resolved, closing
