### ISSUE TITLE
fruit operculum and calyptra perianth, fused perianth

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#312]
The terms operculm and calyptra were requested for describing Eucalyptus fruits. Suggest we name them fruit operculum and fruit calyptra for clarity.

proposed definition of fruit operculum A cardinal organ part that is the apical part of a capsular fruit that separates from the rest of the capsule (the fruit calyptra) during dehiscence. part_of fruit

Comment: Found in Eucalyptus.

Question: Is is a cardinal organ part (formed from a single carpel) or collective organ part structure (formed from parts of multiple carpels)?

proposed definition of fruit calyptra: A cardinal organ part that is the basal part of a capsular fruit that separates from the fruit operculum during dehiscence. part_of fruit

Comment: Found in Eucalyptus. The calyptra may remain attached to the plant after the fruit operculum dehisces.

Question: is the calyptra actually the base of the fruit, or it is an enlarged hypanthium that surrounds the fruit?

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/312](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/312)

**Comment by btsinn** [comment]
I recommend the following revisions be made to the def'n and comment of fruit operculum (PO:0025298):

Current def'n: A collective organ part structure that is the apical part of a circumscissile capsular fruit that separates from the rest of the capsule during dehiscence.

Revised def'n: A collective organ part structure of a circumscissile capsular fruit which separates from the remainder of the **_pericarp_** during dehiscence.

Current comment: Develops from the apical portion of a gynoecium. Found in Eucalyptus and other Myrtaceae.

Revised comment: _**Usually**_ develops from the apical portion of a gyneocium. See circumscissile capsule fruit for example species.
