### ISSUE TITLE
vascular shoot system and non-vascular shoot system

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#316]
We may want to add these upper level terms to accommodate parts of vascular or non-vascular plants. I am not suggesting that we propagate all of the children of shoot system under each one, but we could use them for terms that are specific to one or the other. We can use these terms as part of cross product definitions for various classes that occur only in vascular or non-vascular plants.

Proposed definitions: 
non-vascular shoot system: A shoot system that does not have as part vascular tissue.
comment: Does not have any xylem of phloem, but may have other conducting cells, such hydroids or leptoids. Can occur in both the gametophytic and sporophytic phases of non-vascular plants.

Child of non-vascular shoot system is gametophore. Technically, the sporophyte of a bryphyte is also a non-vascular shoot system \(since it doesn't have roots\).
subsets for bryophytes and pteridophytes

vascular shoot system: A shoot system that has as part a vascular system \(or vascular tissue?\).
comment: Has xylem and/or phloem. Occurs only in the sporophytic phase of vascular plants.
participates\_in sporophytic phase

If we accept these terms, suggest changing definitions of leaf and non-vascular leaf to "A leaf that is part of a non-vascular/vascular shoot system. This would be better than the current definitions which reference their taxonomy \(part of a vascular or non-vascular plant\).

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/316](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/316)

**Comment by cooperl09** [comment]
Resolved, closing
