### ISSUE TITLE
lemma and palea

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#381]
Existing def:
lemma ([PO:0009037](http://purl.obolibrary.org/obo/PO_0009037)): In a grass floret, the lower of two bracts enclosing a flower. [source: APWeb:Glossary, GR:pj] 

Proposed def: A flower bract that is part of a spikelet and is the lower of two bracts enclosing a spikelet floret.

Comment: Found in Poaceae such as Zea mays. If you are annotating to this structure for Zea mays or other grasses, please also add an annotation to the corresponding spikelet type. Choose the most specific term possible from: spikelet ([PO:0009051](http://purl.obolibrary.org/obo/PO_0009051)), ear spikelet ([PO:0006320](http://purl.obolibrary.org/obo/PO_0006320)), ear pedicellate spikelet ([PO:0006348](http://purl.obolibrary.org/obo/PO_0006348)), ear sessile spikelet ([PO:0006349](http://purl.obolibrary.org/obo/PO_0006349)), tassel spikelet ([PO:0006309](http://purl.obolibrary.org/obo/PO_0006309)), tassel pedicellate spikelet ([PO:0006312](http://purl.obolibrary.org/obo/PO_0006312)), tassel sessile spikelet ([PO:0006311](http://purl.obolibrary.org/obo/PO_0006311)).

Was part_of Poaceae floret, but made part_of spikelet, because it is a bract, and by definition, bracts are not part of a flower.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/381](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/381)

**Comment by cooperl09** [comment]
Revised definitions slightly: 

palea (PO:0009038)
Was: A flower bract (PO:0009034) that is the upper/distal of the two bracts (PO:0009055) enclosing a (PO:0009082) spikelet floret. 

Revised:  The upper (distal), usually smaller, of the pair of flower bracts (PO:0009034) enclosing a (PO:0009082) spikelet floret. 


lemma (PO:0009038): 
Was: A flower bract (PO:0009034) that is the lower of the two bracts (PO:0009055) enclosing a (PO:0009082) spikelet flore
Revised: The lower, usually larger, of the pair of flower bracts (PO:0009034) enclosing a (PO:0009082) spikelet floret.
