### ISSUE TITLE
vegetative bud (PO:0000058)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#463]
We have terms for axillary and terminal vegetative buds that are defined as developing into either a long or short shoot. This is not appropriate, because those are not the only things the buds can develop into, and the terminology "long shoot" and "short shoot" are not used in every taxon.

I suggest we redefine them similar to their parent term, vegetative bud.

vegetative bud \([PO:0000058](http://purl.obolibrary.org/obo/PO_0000058)\), current def.: A bud that develops into a shoot system that has as organ parts only vegetative organs. 

This is problematic, because we don't actually have a term for vegetative organs, but I don't want to get into it at this point. Just focus on fixing axillary and terminal vegetative bud so we can use them a parents for other terms. We can come back and look at the definitions of vegetative and reproductive bud at a later time.

axillary vegetative bud \([PO:0004712](http://purl.obolibrary.org/obo/PO_0004712)\), current definition: An axillary bud that develops into a long or short shoot.

axillary vegetative bud \([PO:0004712](http://purl.obolibrary.org/obo/PO_0004712)\), proposed definition: An axillary bud \([PO:0004712](http://purl.obolibrary.org/obo/PO_0004712)\) that develops into a shoot system \([PO:0009006](http://purl.obolibrary.org/obo/PO_0009006)\) that has as organ parts only vegetative organs. 

terminal vegetative bud \([PO:0004716](http://purl.obolibrary.org/obo/PO_0004716)\), current definition: A terminal bud that develops into a long or short shoot.

terminal vegetative bud \([PO:0004716](http://purl.obolibrary.org/obo/PO_0004716)\), proposed definition: A terminal bud \([PO:0004713](http://purl.obolibrary.org/obo/PO_0004713)\) that develops into a shoot system \([PO:0009006](http://purl.obolibrary.org/obo/PO_0009006)\) that has as organ parts only vegetative organs. 

The new term, areole bud \([PO:0025353](http://purl.obolibrary.org/obo/PO_0025353)\), will be a subtype of axillary vegetative bud.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/463](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/463)

**Comment by cooperl09** [comment]
Resolved, closing.
