### ISSUE TITLE
scar tissue/necrotic tissue

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#481]
This could be useful for describing a number of plant structures, such as the hilum or a leaf scar, or the scar left by any abscission zone.

From Esau: scar tissue or cicatrice tissue: Composed of necrotic cells injured by the wounding and subjacent cells impregnated with protective substances. 

A term for necrotic tissue would also be useful for describing plant disease symptoms. It may need to be defined slightly differently from scar tissue.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/481](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/481)

**Comment by cooperl09** [comment]
We decided that we do not need this term a this time.
