### ISSUE TITLE
fruit pedicel

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#487]
I removed the relation "fruit pedicel part-of fruit", because it is not correct. A fruit pedicel is the branch that holds up a fruit, not part of the fruit.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/487](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/487)

**Comment by btsinn** [comment]
Fruit pedicel (PO:0004536) has been renamed to infructescence pedicel (PO:0004536) to discern between pedicels of infructescences vs. a new fruit pedicel (PO:0030114) term which refers to pedicels of solitary fruits.

Please refer to issues #89, #487, #672, #673, and #668 for additional context.
--------------------------------------------------------------------------------------------------------
infructescence pedicel (PO:0004536)

Renaming of: _fruit pedicel (PO:0004536)_

Previous def'n: 
An infructescence branch (PO:0025243) that supports an individual fruit (PO:0009001).

Revised def'n: 
_A pedicel (PO:0030112) that terminates in a fruit (PO:0009001) in an infructescence (PO:0006342)._

Previous comment: 
The ultimate branch in an infructescence.

Revised comment: 
_An infructescence pedicel is the ultimate axis in an infructescence._

Current synonyms: 
pedicelo del fruto (Spanish, exact), 果柄 (Japanese, exact)

Revised synonyms: 
_No revisions._ 

---------------------------------------------------------------------------------------------

fruit pedicel (PO:0030114)

Def'n:  
_A pedicel (PO:0030112) that terminates in a fruit (PO:0009001)._

Comment: 
_None._

Synonyms: 
_pedicelo del fruto (Spanish, broad)_

**Comment by btsinn** [comment]
Fruit pedicel (PO:0030114)
Revised def'n: 
A pedicel (PO:0030112) that bears a fruit (PO:0009001).

-----------------------------------------------------------------------

infructescence pedicel (PO:0004536)
Revised def'n:
A pedicel (PO:0030112) that bears a fruit (PO:0009001) in an infructescence (PO:0006342).
