### ISSUE TITLE
vascular system

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#50]
The PO is_a hierarchy is:

+/ [PO:0009011](http://purl.obolibrary.org/obo/PO_0009011) ! plant structure [DEF: "Any morphological or anatomical feature of a plant."]
++is_a [PO:0009007](http://purl.obolibrary.org/obo/PO_0009007) ! tissue [DEF: "Group of cells organized into a structural and functional unit; the component cells may be alike (simple tissue) or varied (complex tissue)."]
+++is_a [PO:0000034](http://purl.obolibrary.org/obo/PO_0000034) ! vascular system ***  [DEF: "Total of the vascular tissues in their specific arrangement in a plant or plant organ."]

This is different from animal anatomy ontologies which are organized by CARO in which anatomical system is a sibling to (portion of) tissue

E.g.

+is_a [CARO:0000003](http://purl.obolibrary.org/obo/CARO_0000003) ! anatomical structure [DEF: "Material anatomical entity that has inherent 3D shape and is generated by coordinated expression of the organism's own genome."]
++is_a [CARO:0000043](http://purl.obolibrary.org/obo/CARO_0000043) ! portion of tissue ***  [DEF: "Anatomical structure, that consists of similar cells and intercellular matrix, aggregated according to genetically determined spatial relationships."]
++is_a [CARO:0000054](http://purl.obolibrary.org/obo/CARO_0000054) ! anatomical group [DEF: "Anatomical structure consisting of at least two non-overlapping organs, multi-tissue aggregates or portion of tissues or cells of different types that does not constitute an organism, organ, multi-tissue aggregate, or portion of tissue."]
+++is_a [CARO:0000011](http://purl.obolibrary.org/obo/CARO_0000011) ! anatomical system ***  [DEF: "Anatomical group that is has as its parts distinct anatomical structures interconnected by anatomical structures at a lower level of granularity."]

Would the CARO definition of tissue work for plants?

can we have 'anatomical system' as sibling to tissue underneath plant structure?

Also - the def of vascular system is:

[PO:0000034](http://purl.obolibrary.org/obo/PO_0000034) ! vascular system [DEF: "Total of the vascular tissues in their specific arrangement in a plant or plant organ."]

The disjunction (or) is confusing. Does an individual plant have a single vascular system, with different parts (e.g. flower vascular system)? Or does an individual plant have multiple separate vascular systems (e.g. flower vascular system)

If the former, then the relation between X vascular system and vascular system should be part_of. The definitions should read "the part of the vascular system that is in X"

If the latter, then the relation should be is_a, and the definitions should read "a vascular system that is in X"

Currentlyin PO all relations are is_a, with the exception of

[PO:0000035](http://purl.obolibrary.org/obo/PO_0000035) ! cotyledon vascular system [DEF: "Vascular system of the cotyledon."]

The definition follows the same structure as the other X vascular system terms. Any reason for the difference in ontology structure?

My preference would be to define VS as the entire system running throughout the plant. We would then have terms like "X vasculature" which would be is_a vasculature, part_of X. This would require a new term "vasculature" which would be defined as a segment of the VS in an organ.

PO also states that "flower vascular system" is_a flower. This is wrong, the relation should be part_of.

Reported by: cmungall

Original Ticket: [obo/plant-ontology-po-term-requests/50](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/50)

**Comment by cooperl09** [comment]
See also #41
