### ISSUE TITLE
flower development stage

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#500]
[PO:0007615](http://purl.obolibrary.org/obo/PO_0007615)

Changing definition to reflect our current standard form.

Current def.: Stages of development of a flower defined by characteristic morphological, structural, histological or other visible features.

New proposed def: A collective plant organ structure development stage ([PO:0025338](http://purl.obolibrary.org/obo/PO_0025338)) that has as primary participant a flower ([PO:0009046](http://purl.obolibrary.org/obo/PO_0009046)).

Comment: Defined by characteristic morphological, structural, histological, or other visible features.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/500](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/500)

**Comment by cooperl09** [comment]
Revised definition:
flower development stage (PO:0007615):  A reproductive shoot system development stage (PO:0025530) that occurs during the interval between the onset of a flower meristem transition stage (PO:0025588) and the end of a flowering stage (PO:0007616) in an individual flower (PO:000904). 

added relation: flower development stage has_ participant flower 
Comment: This term and its sub-classes apply to an individual flower (PO:000904). During this stage, a flower undergoes the process of flower development (GO:0009908), defined as the process whose specific outcome is the progression of the flower over time, from its formation to the mature structure.  For the development stage of a whole plant (PO:0000003), use whole plant flowering stage (PO:0007016).
