### ISSUE TITLE
archegonium initial cell

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#507]
New term.

This arose out of the definition of central cell \(see https://sourceforge.net/tracker/index.php?func=detail&aid=3080937&group\_id=76834&atid=835555\).

archegonial initial cell \([PO:0025510](http://purl.obolibrary.org/obo/PO_0025510)\): An initial cell that is part of an archegonium megagametophyte \([PO:0025282](http://purl.obolibrary.org/obo/PO_0025282)\) and divides to give rise to an archegonium \([PO:0025126](http://purl.obolibrary.org/obo/PO_0025126)\).

[PMID:17041880](http://purl.obolibrary.org/obo/PMID_17041880)

Added archegonium central cell develops from archegonium initial cell. Didn't add archegonium develops from archegonium initial cell, because I think that is only true in gymnosperms.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/507](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/507)

**Comment by cooperl09** [comment]
Resolved, closing
