### ISSUE TITLE
Add relation xrefs

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#524]
Could you edit the relation stanzas to have xrefs to BFO and inverses as follows:

\[Typedef\]
id: participates\_in
name: participates\_in
holds\_over\_chain: part\_of participates\_in
xref: [BFO:0000056](http://purl.obolibrary.org/obo/BFO_0000056)
inverse\_of: has\_participant

\[Typedef\]
id: has\_participant
name: has\_participant
xref: [BFO:0000057](http://purl.obolibrary.org/obo/BFO_0000057)

\[Typedef\]
id: located\_in
name: located\_in
xref: [RO:0001025](http://purl.obolibrary.org/obo/RO_0001025)

Reported by: cmungall

Original Ticket: [obo/plant-ontology-po-term-requests/524](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/524)

**Comment by cooperl09** [comment]
Done.  located in already had the RO xref
