### ISSUE TITLE
spine petiole

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#535]
A petiole that is sclerified and persistent.  

The petiole abcisses longitudinally and the blade withers.

Reported by: dws409

Original Ticket: [obo/plant-ontology-po-term-requests/535](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/535)

**Comment by austinmeier** [comment]
Created new child term of petiole(PO:0020038): spine petiole (PO:0025613) 
Proposed def’n: A petiole (PO:0020038) that is sclerified and persistent. 
Added xref PO_GIT:535

**Comment by cooperl09** [comment]
Please add comment from above: "The petiole abcisses longitudinally and the blade withers.

replace 'blade" with leaf lamina (PO:id)

**Comment by austinmeier** [comment]
Comment added:  The petiole (PO:0020038) abcisses longitudinally and the leaf lamina (PO:0020039) withers.
