### ISSUE TITLE
ear inflorescence (PO:0020136) and its child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#536]
We need to revise this definition and those of the child terms:

ear inflorescence \([PO:0020136](http://purl.obolibrary.org/obo/PO_0020136)\): The distal part of a lateral \(axillary\) branch in Zea that bears the functionally-carpellate florets in a highly contracted inflorescence. is\_a inflorescence \([PO:0009049](http://purl.obolibrary.org/obo/PO_0009049)\)

part\_of child terms:

\* ear inflorescence branch meristem \([PO:0009110](http://purl.obolibrary.org/obo/PO_0009110)\): An inflorescence branch meristem \([PO:0009105](http://purl.obolibrary.org/obo/PO_0009105)\) that gives rise to a branch of an ear inflorescence \([PO:0020136](http://purl.obolibrary.org/obo/PO_0020136)\). OK

\* central spike of ear \([PO:0006505](http://purl.obolibrary.org/obo/PO_0006505)\)- renamed 'central spike of ear inflorescence' and added PO:ids to the definition: A first order inflorescence axis \([PO:0025104](http://purl.obolibrary.org/obo/PO_0025104)\) that is the central axis of an ear inflorescence \([PO:0020136](http://purl.obolibrary.org/obo/PO_0020136)\).  OK

\*ear meristem \([PO:0009109](http://purl.obolibrary.org/obo/PO_0009109)\): The meristem which gives rise to the female inflorescence or ear in maize.  Needs work

\*ear peduncle \([PO:0006418](http://purl.obolibrary.org/obo/PO_0006418)\): A peduncle of a maize ear, below the lowest ear node. Needs work

\*ear spikelet \([PO:0006320](http://purl.obolibrary.org/obo/PO_0006320)\): Ultimate inflorescence branch of the maize ear. Needs work

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/536](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/536)

**Comment by cooperl09** [comment]
Resolved and closing.
