### ISSUE TITLE
phyllome development stage and children

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#548]
Proposed new child of plant organ development stage ([PO:0025339](http://purl.obolibrary.org/obo/PO_0025339))
phyllome development stage (new [PO:0025579](http://purl.obolibrary.org/obo/PO_0025579)): A plant organ development stage ([PO:0025339](http://purl.obolibrary.org/obo/PO_0025339)) that has aprimary participant a phyllome ([PO:0025023](http://purl.obolibrary.org/obo/PO_0025023)).

Proposed children of phyllome development stage, current and revised definitions:
lemma development stage ([PO:0001047](http://purl.obolibrary.org/obo/PO_0001047)):Stages of development of the lemma defined by characteristic morphological, structural, histological or other visible features. 

Revised def'n: A phyllome development stage ([PO:0025579](http://purl.obolibrary.org/obo/PO_0025579)) that has as a primary participant a lemma ([PO:0009037](http://purl.obolibrary.org/obo/PO_0009037)).

lodicule development stage ([PO:0001049](http://purl.obolibrary.org/obo/PO_0001049)):Stages of development of the lodicule defined by characteristic morphological, structural, histological or other visible features. 

Revised def'n: A phyllome development stage ([PO:0025579](http://purl.obolibrary.org/obo/PO_0025579)) that has as a primary participant a lodicule ([PO:0009036](http://purl.obolibrary.org/obo/PO_0009036)).
palea development stage ([PO:0001048](http://purl.obolibrary.org/obo/PO_0001048)): Stages of development of the palea defined by characteristic morphological, structural, histological or other visible features. 

Revised def'n: A phyllome development stage ([PO:0025579](http://purl.obolibrary.org/obo/PO_0025579)) that has as a primary participant a palea ([PO:0009038](http://purl.obolibrary.org/obo/PO_0009038)). 

Reported by: lauramoore1859

Original Ticket: [obo/plant-ontology-po-term-requests/548](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/548)

**Comment by cooperl09** [comment]
Added a new relation: 
phyllome development stage (PO:0025579) part_of shoot system development stage (PO:0025527).  See #582.
Closing this tracker for.  Can be reopened later if needed.
