### ISSUE TITLE
leaf development stage (PO: 0001050) and its children

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#555]
Proposed new children of leaf development stage ([PO:0001050](http://purl.obolibrary.org/obo/PO_0001050)):

vascular leaf development stage (new PO:id): A leaf development stage ([PO:0001050](http://purl.obolibrary.org/obo/PO_0001050)) that begins with the vascular leaf initiation stage ([PO:0007040](http://purl.obolibrary.org/obo/PO_0007040)) and ends with the vascular leaf senescence stage ([PO:0001054](http://purl.obolibrary.org/obo/PO_0001054)). 

non-vascular leaf development stage (new PO:id): A leaf development stage ([PO:0001050](http://purl.obolibrary.org/obo/PO_0001050)) that begins with the non-vascular leaf initiation stage and ends with the non-vascular leaf senescence stage. 

Reported by: atkinsob

Original Ticket: [obo/plant-ontology-po-term-requests/555](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/555)

**Comment by cooperl09** [comment]
Proposed revision to vascular leaf development stage (PO:0025570): 
Currently defined as: 
A leaf development stage (PO:0001050) which begins with the onset of the vascular leaf initiation stage (PO:0001051) and ends with the termination of the vascular leaf senescence stage (PO:0001054). 

New: 
vascular leaf development stage (PO:0025570): A leaf development stage (PO:0001050) that occurs during the interval between the onset of the vascular leaf initiation stage (PO:0001051) and the termination of the vascular leaf senescent stage (PO:0001054).

@rlwalls2008

**Comment by rlwalls2008** [comment]
Great!
