### ISSUE TITLE
vascular leaf primordium adaxial side (PO:0004726)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#570]
Propose term and definition revision: 

vascular leaf primordium adaxial side ([PO:0004726](http://purl.obolibrary.org/obo/PO_0004726)): A portion of vascular leaf primordium ([PO:0000017](http://purl.obolibrary.org/obo/PO_0000017)) that faces the shoot apical meristem ([PO:0020148](http://purl.obolibrary.org/obo/PO_0020148)) and develops into the adaxial (upper) side of the leaf lamina ([PO:0020039](http://purl.obolibrary.org/obo/PO_0020039)). 

Related term: [plant-ontology-po-term-requests:#571]

Reported by: atkinsob

Original Ticket: [obo/plant-ontology-po-term-requests/570](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/570)

**Comment by cooperl09** [comment]
accepted, closing
