### ISSUE TITLE
vascular leaf primordium abaxial side (PO:0004725)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#571]
Propose term and definition revision: 

vascular leaf primordium abaxial side ([PO:0004725](http://purl.obolibrary.org/obo/PO_0004725)): A portion of vascular leaf primordium ([PO:0000017](http://purl.obolibrary.org/obo/PO_0000017)) that faces away from the shoot apical meristem ([PO:0020148](http://purl.obolibrary.org/obo/PO_0020148)) and develops into the abaxial (lower) side of the leaf lamina ([PO:0020039](http://purl.obolibrary.org/obo/PO_0020039)). 

Related term: [plant-ontology-po-term-requests:#570]

Reported by: atkinsob

Original Ticket: [obo/plant-ontology-po-term-requests/571](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/571)

**Comment by cooperl09** [comment]
Accepted, closing
