### ISSUE TITLE
Leaf lamina tip (PO:0025589)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#574]
Propose new term

leaf lamina tip ([PO:0025589](http://purl.obolibrary.org/obo/PO_0025589)): A leaf tip ([PO:0025142](http://purl.obolibrary.org/obo/PO_0025142)) that is the distal portion of the leaf lamina ([PO:0020039](http://purl.obolibrary.org/obo/PO_0020039)).

comment: This is the portion of the leaf lamina ([PO:0020039](http://purl.obolibrary.org/obo/PO_0020039)) that is furthest away from the stem ([PO:0009047](http://purl.obolibrary.org/obo/PO_0009047)).

Reported by: atkinsob

Original Ticket: [obo/plant-ontology-po-term-requests/574](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/574)

**Comment by cooperl09** [comment]
Accepted and closing
