### ISSUE TITLE
Phyllome founder cell (PO:0025586) and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#575]
New terms added:
phyllome founder (cell [PO:0025586](http://purl.obolibrary.org/obo/PO_0025586)): A plant cell ([PO:0009002](http://purl.obolibrary.org/obo/PO_0009002)) that is part of the phyllome anlagen ([PO:0025430](http://purl.obolibrary.org/obo/PO_0025430)).

Comment: As a group, the phyllome founder cells encompass several layers of the shoot apical meristem ([PO:0020148](http://purl.obolibrary.org/obo/PO_0020148)) and form a phyllome anlagen ([PO:0025430](http://purl.obolibrary.org/obo/PO_0025430)). Founder cells do not function as stem cells but rather have a determinate fate and can be defined by histological, clonal and molecular criteria.

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/575](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/575)

**Comment by cooperl09** [comment]
Updated definition:  phyllome founder cell (PO:0025586): A native plant cell (PO:0025606) that is part of the phyllome anlagen (PO:0025430). 

Comment: As a group, the phyllome founder cells encompass several layers of the shoot apical meristem (PO:0020148) and form a phyllome anlagen (PO:0025430). Founder cells do not function as stem cells but rather have a determinate fate and can be defined by histological, clonal and molecular criteria.
