### ISSUE TITLE
meristem L1, L2 and L3 layers

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#576]
Propose revised names and definitions for the following terms:
meristem L1 ([PO:0009020](http://purl.obolibrary.org/obo/PO_0009020)): The outermost layer of a shoot apical meristem that gives rise to a shoot epidermis.

revised name and def'n: meristem L1 layer ([PO:0009020](http://purl.obolibrary.org/obo/PO_0009020)): A portion of meristem tissue ([PO:0009013](http://purl.obolibrary.org/obo/PO_0009013)) that is the outermost layer of a shoot apical meristem ([PO:0020148](http://purl.obolibrary.org/obo/PO_0020148)) and gives rise to a shoot system epidermis ([PO:0006035](http://purl.obolibrary.org/obo/PO_0006035)).

Continued from old tracker: [plant-ontology-po-term-requests:#150]

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/576](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/576)

**Comment by cooperl09** [comment]
This has been resolved.
