### ISSUE TITLE
root meristem (PO:0006085) and child terms

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#577]
There is an issue with the child terms of root apical meristem [PO:0020147](http://purl.obolibrary.org/obo/PO_0020147): These be "gives rise to a xxxx root- not part of a xxxx root.? 

root apical meristem [PO:0020147](http://purl.obolibrary.org/obo/PO_0020147): A root meristem ([PO:0006085](http://purl.obolibrary.org/obo/PO_0006085)) formed at the apex of a root ([PO:0009005](http://purl.obolibrary.org/obo/PO_0009005)), including those originating from an lateral root apical meristem ([PO:0006020](http://purl.obolibrary.org/obo/PO_0006020)).

primary root apical meristem ([PO:0006081](http://purl.obolibrary.org/obo/PO_0006081)): A root apical meristem ([PO:0020147](http://purl.obolibrary.org/obo/PO_0020147)) that is part of a primary root ([PO:0020127](http://purl.obolibrary.org/obo/PO_0020127)). 

Revised definition: A root apical meristem ([PO:0020147](http://purl.obolibrary.org/obo/PO_0020147)) that gives rise to a primary root ([PO:0020127](http://purl.obolibrary.org/obo/PO_0020127)). 

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/577](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/577)

**Comment by austinmeier** [comment]
Revised definition of lateral root tip (PO:0000027)- A root tip (PO:0000025) of a lateral root (PO:0020121).

**Comment by cooperl09** [comment]
Please add curator name (yours) and xref to this tracker.

**Comment by austinmeier** [comment]
Fixed.
