### ISSUE TITLE
gamete (PO:0025006)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#58]
I was wondering why there is no gamete term in PO.  Sperm cell and egg cell are part of children of male and female gametophyte, respectively, but they are not siblings under a common parent 'gamete'.  Was this term not deemed necessary?

Thanks,

Tanya

Reported by: tberardini

Original Ticket: [obo/plant-ontology-po-term-requests/58](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/58)

**Comment by austinmeier** [comment]
see #610 for extended discussion
