### ISSUE TITLE
New term: ear infructescence ( PO:0025597)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#580]
I think we need to create a term 'ear infructescence'.  Once the kernels have formed, it is no longer an inflorescence.  
See related tracker: [plant-ontology-po-term-requests:#536]

Proposed definition: ear infructescence (new PO:id): An infructescence ([PO:0006342](http://purl.obolibrary.org/obo/PO_0006342)) composed of compacted rows of caryopses (grains or kernels).   

develops_from: ear inflorescence [PO:0020136](http://purl.obolibrary.org/obo/PO_0020136)

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/580](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/580)

**Comment by cooperl09** [comment]
This is done, closing this tracker.
