### ISSUE TITLE
plant organ development stage should not be part of shoot system development stage

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#582]
Plant organ development stage ([PO:0025339](http://purl.obolibrary.org/obo/PO_0025339)) currently has a part of relation to shoot system development stage ([PO:0025527](http://purl.obolibrary.org/obo/PO_0025527)), but this is not correct, because root development stage is a type of plant organ development stage that is not part of a shoot system development stage.

You could say that phyllome development stage and and floral organ development stage are part of a shoot system development stage.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/582](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/582)

**Comment by cooperl09** [comment]
Thai has been resolved.  Added a new relation:  phyllome development stage (PO:0025579) part_of shoot system development stage (PO:0025527). For more information on the phyllome development stage (PO:0025579), please see #548 .
