### ISSUE TITLE
adventitious root epidermis ( PO:0006039)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#598]
Request from collaborators at New Phytologist: this needs to be renamed and def'n revised.

'adventitious root epidermis '( [PO:0006039](http://purl.obolibrary.org/obo/PO_0006039)) -  This is an example of an official PO child term referring to a potential parent term that does not itself exist in the PO.

Agreed!

Currently this is a root epidermis ([PO:0006036](http://purl.obolibrary.org/obo/PO_0006036)) that is part of a shoot-borne root ([PO:0000042](http://purl.obolibrary.org/obo/PO_0000042)) 

Propose revised name: shoot-borne root epidermis ( [PO:0006039](http://purl.obolibrary.org/obo/PO_0006039)): A portion of root epidermis ([PO:0006036](http://purl.obolibrary.org/obo/PO_0006036)) that is part of a shoot-borne root ([PO:0000042](http://purl.obolibrary.org/obo/PO_0000042)).

Will make "adventitious root epidermis" a broad synonym

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/598](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/598)

**Comment by cooperl09** [comment]
Fixed and accepted. Closing this issue.
