### ISSUE TITLE
carpel abaxial epidermis

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#600]
Request: carpel abaxial epidermis
Def: A portion of carpel epidermis that covers the abaxial/lower surface of a carpel.
Ref: http://onlinelibrary.wiley.com/doi/10.1111/tpj.12834/full

Internal ref:https://pubsearch.arabidopsis.org/pubsearch/Display?acc=[term:3250496](http://purl.obolibrary.org/obo/term_3250496)

Thanks.

Reported by: tberardini

Original Ticket: [obo/plant-ontology-po-term-requests/600](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/600)

**Comment by cooperl09** [comment]
We recommend using the existing term:  carpel epidermis- PO:0025096, as after a survey of the figure in the literature (http://onlinelibrary.wiley.com/doi/10.1111/tpj.12834/suppinfo), it is not clear that the statement is referring to the abaxial epidermis of the carpel.  
Also, it is unclear whether that is commonly used term.
