### ISSUE TITLE
hop cone

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#601]
How do we annotate a 'hop cone'?
Is it an equivalent of 'infructuscence'.

Reported by: jaiswalp

Original Ticket: [obo/plant-ontology-po-term-requests/601](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/601)

**Comment by austinmeier** [comment]
created new term: megasporangiate strobilus (PO:0005032)
proposed def'n: A strobilus (PO:0025083) that bears ovules.
is_a: strobilus (PO:0025083)
synonyms: female cone (related), macrostrobili (related), macrostrobilius (related), megastrobuilus (related), ovulate cone (narrow), macrostrobilus (related)

created new term: microsporangiate strobilus (PO:0005031)
proposed def'n: a strobilus (PO:0025083) that bears pollen.
is_a: strobilus (PO:0025083)
synonyms: pollen cone (narrow), male cone (related) microstrobilus (narrow)

**Comment by cooperl09** [comment]
Please add 'hop cone' as a narrow synonym of megasporangiate strobilus (PO:0005032).  Also, please see comments on #168 strobilus tracker.
