### ISSUE TITLE
lupulin glands- glandular trichomes from Humulus lupulus

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-ontology#602]
The lupulin glands are part of the hop cone, and the source of the aromatics and other compounds.  

These are glandular trichomes,  see: http://www.plantcell.org/content/20/1/186.full

glandular trichome PO:0004509: A trichome that secretes or sequesters a portion of plant substance.
Please see tracker #53

We could make lupulin gland a subclass_of glandular trichome or a narrow synonym.  If it is needed to annotate datasets, a stand alone term would be preferable.

**Comment by austinmeier** [comment]
Proposed new term:  lupulin gland
proposed def'n: A glandular trichome (PO:0004509) that synthesizes terpenophenolic resins and prenylflavonoids.
DBXref:  PMID:18223037,
is_a glandular trichome (PO:0004509)
part_of strobilus (PO:0025083)

It seems the thing that makes them unique from other glandular trichomes are the production of Xanthohumol (3′-[3,3-dimethyl allyl]-2′,4′,4-trihydroxy-6′-methoxychalcone), the principal prenylated flavonoid in hops.
-http://www.sciencedirect.com/science/article/pii/S0031942204001876

Therefore, lupulin glands are unique and exclusive organs responsible for contents of bitter acids and polyphenols in hop cone.  
http://onlinelibrary.wiley.com/doi/10.1111/ijfs.12825/abstract

**Comment by austinmeier** [comment]
Created new term: 
lupulin gland (PO:0005030)
Def: A glandular trichome (PO:0004509) that synthesizes terpenophenolic resins and prenylflavonoids.
DBXrefs: PMID:18223037, CHEBI:66331
Xref: PO_GIT:602
is_a: glandular trichome (PO:0004509)

Comment: One of the major chalconoids from hops is xanthohumol (CHEBI:66331).

**Comment by cooperl09** [comment]
This looks fine.Removed the part_of strobilus (PO:0025083).  Note that we did not make it part_of the megasporangiate strobilus (PO:0005032), as there is evidence from the literature that the lupulin glands do occur on the leaves and also in the male cones, although they are most abundant on the female strobili.  see: http://www.plantcell.org/content/20/1/186.full.
