### ISSUE TITLE
     PO:0020025 micropyle

### ISSUE THREAD

**Issue by tberardini** [Planteome/plant-ontology#609]
Hi there,

micropyle (PO:0020025) generated 1 warning: The terms micropyle (GO:0070825) and micropyle (PO:0020025) share the name or synonym "micropyle."

Would it be possible to switch the primary term name and synonym, micropyle and ovular micropyle?

Thanks very much,

Tanya

**Comment by cooperl09** [comment]
Yes, I think that would work, I will just run it by our plant morphology expert.  Thanks for letting us know.

**Comment by tberardini** [comment]
Thanks, Laurel!

**Comment by austinmeier** [comment]
changed micropyle(PO:0020025) name to plant ovule micropyle
revised def’n to include PO:IDs:  A plant anatomical space (PO:0025117) that is enclosed by and forms an opening in an integument at the apex of a plant ovule (PO:0020003).
added xref: PO_GIT:609
add narrow synonym: micropyle, and plant ovular micropyle

**Comment by tberardini** [comment]
Thanks!
