### ISSUE TITLE
Rename PO:gamete  as plant gamete or merge into CL:gamete?

### ISSUE THREAD

**Issue by tberardini** [Planteome/plant-ontology#610]
PO:gamete
Def: 	
    A native plant cell (PO:0025606) that has half the chromosome complement of the sporophyte and is capable of fertilization to create a plant zygote (PO:0000423). 

CL:gamete
Def:A mature sexual reproductive cell having a single set of unpaired chromosomes.

**Comment by phismith** [comment]
can we rename it PO:plant gamete, defined as a plant cell that is a
CL:gamete?

**Comment by tberardini** [comment]
Sounds like a good solution.  Thanks.

**Comment by austinmeier** [comment]
renamed gamete(PO:0025006) to plant gamete(PO:0025006)
added xref PO_GIT:610

**Comment by tberardini** [comment]
Thanks!
