### ISSUE TITLE
Stem Hairiness

### ISSUE THREAD

**Issue by maxglycine** [Planteome/plant-ontology#611]
[Term]
id: TO:0000879
name: stem hairiness
def: "A stem anatomy and morphology trait (TO:0000361) which is associated with the presence or absence of hair on the stem (PO:0009047)." [PO:0009047, TO:moorel]
comment: Refer to hairy (PATO:0000454): A pilosity quality inhering in a bearer by virtue of the bearer's being covered with hair or hairlike projections.
xref: PATO:0000454
is_a: TO:0000361 ! stem anatomy and morphology trait
created_by: moorel
creation_date: 2012-10-09T15:17:12Z

It is not clear to me if "Stem hairiness" is due to an increase in the number of hairs (pubescence) on the stem or if the hairs are longer than normal and thus the stem "appears" to be hairier. Should the definition be changed to stipulate the hairiness measurement or should the name be changed to maybe "stem hair" which to me, seems to fit the current definition better than "hairiness".

**Comment by rlwalls2008** [comment]
Should this also refer to the PO term for trichome, or can the hairs be some other kind of structure? I only now of trichomes, but who knows.

**Comment by cooperl09** [comment]
This should be on the TO tracker, not the PO one. :\

**Comment by marieALaporte** [comment]
This TO term refers to a PATO term through an xref.  What is the semantics behind xref? Should xref used only for "equivalent class" or can it have a broader meaning like "somehow related to"? How can the difference be made?
I looked at the obo spec but it is still unclear.

**Comment by marieALaporte** [comment]
This issue was moved to Planteome/plant-trait-ontology#405
