### ISSUE TITLE
Create a standard directory layout

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-ontology#614]
follow the pattern here:
https://github.com/Planteome/plant-trait-ontology

In particular

 * remove to-release-files (github manages releases for you)
 * make the release products po.owl and po.obo
 * have a distinct editors / snapshot file (recommended name: po-edit.obo)

 recommended:

 * add a .travis.yml file

I can do any or all, given the go-ahead. Note this may have implications for your amigo1-nightly-snapshot

**Comment by cmungall** [comment]
I had been pointing the OBO library release at the release-files directory, since that seemed to be the file for releases. Let's fix this.

**Comment by cmungall** [comment]
@elserj -- this is done and ready to go

For AmiGO1 I suggest using:

http://purl.obolibrary.org/obo/po/subsets/po-basic.obo

Explanation: The "basic" subset of obo format is geared towards legacy applications like AmiGO 1. subsets/po-basic.obo only includes is_a and part_of relationships, and no logical definitions

For AmiGO 2, take your pick
http://purl.obolibrary.org/obo/po.owl
http://purl.obolibrary.org/obo/po.obo

**Comment by cooperl09** [comment]
The version loaded on the Plant Ontology website should have all the relations.  It should be the file that is analogous to plant-ontology-assert.obo file, in other words the po.obo file.

**Comment by cmungall** [comment]
Clarification: use http://purl.obolibrary.org/obo/po.obo for amigo1 too

**Comment by cooperl09** [comment]
Thank you.

**Comment by cooperl09** [comment]
So we can keep working in the plant-ontology.obo (editor's version), correct?

**Comment by cmungall** [comment]
Correct. I updated the README to include this information.
