### ISSUE TITLE
endodermis, cortex, and ground tissue cell types (new term)

### ISSUE THREAD

**Issue by jaiswalp** [Planteome/plant-ontology#618]
Suggest adding following terms

endodermis cell (new) i.e. is_a ground tissue cell (new) is_a PO:0025606 : native plant cell
-- it is also part_of PO:0000252 : endodermis
cortex cell (new) i.e. is_a ground tissue cell (new) is_a PO:0025606 : native plant cell
-- it is also part_of PO:0005708 : cortex

**Comment by jaiswalp** [comment]
and develops_from root cortex-endodermis initial cell ; PO:0000060

**Comment by tberardini** [comment]
@cooperl09 or anyone else monitoring this ticket: Did 'endodermis cell' ever get added? I was going to request it also. I don't see it in the current version of PO visible in Planteome.

**Comment by tberardini** [comment]
For endodermal cell:

A native plant cell (PO:0025606) that is part of a portion of endodermis (PO:0000252).

**Comment by cooperl09** [comment]
Added new term: 
endodermis cell (PO:0025624): A ground tissue cell (PO:0025030) that is part of a portion of endodermis (PO:0000252).
 is part_of  endodermis (PO:0000252) and develops_from a root cortex-endodermis initial cell (PO:0000060)

**Comment by cooperl09** [comment]
Added new term:
cortex-endodermis initial cell (PO:0025625): An initial cell (PO:0004011) that produces cortex (PO:0005708) and endodermis (PO:0000252).
