### ISSUE TITLE
questions about terms for IEDB

### ISSUE THREAD

**Issue by rvita** [Planteome/plant-ontology#624]
Hi, I work on the Immune Epitope Database (www.iedb.org) and we are working with the Human disease ontology (DO) to create formal logical definitions for food allergic diseases. In this process, we are using several PO terms, but a few terms that we need are missing or are causing us trouble. I want to ask if the needed terms and or edits are within your scope before making formal term requests. We understand that correct plant biology may not align with the commonly used medical terms, but maybe you can suggest ways for us to deal with this or another ontology that may be better suited to our needs?
1) fruit	PO_0009001: for this term, nut and grain are synonyms. We want to logically define fruit, nut and grain allergies as separate diseases based upon the allergy being to a different PO term. Is it possible to split the term or make more specific child terms?
2) vegetable: this term does not exist in PO, but we want to logically define vegetable allergy as a disease. Is this term something that PO could add?
3) legume: this term does not exist in PO, but we want to logically define a legume allergy. Is this term something that PO could add?
4) cereal and pseudocereal: these are terms used to group foods allergens, but I am not sure if they have any basis in botany? Do you think they are reasonable terms or should we try different terms?
thanks very much. we appreciate your ontology!
-Randi

**Comment by cmungall** [comment]
I think you want some kind of intermediate product or food ontology, that can in turn be linked to PO (or CHEBI, or ENVO, ...). cc @pbuttigieg

**Comment by pbuttigieg** [comment]
Interesting timing - I'm about to enter a call about creating a food ontology which seems more appropriate for your requests, @rvita. ENVO does indeed have several food terms, but a fully fledged food ontology would be a better intermediary between needs like yours and anatomy or other such ontologies.

If there's urgency, we can certainly add the classes and definitions you need to ENVO (we do, after all, have zebra milk in there) and then surrender them to a food ontology when it emerges.

**Comment by rvita** [comment]
Hi thanks, looking at ENVO, it already has quite a few of the terms we need. So we would be happy if you could add 'vegetable food product' 'nut food product' and 'legume food product' for now and we can later move to the food ontology. Because of the food allergic diseases, we have been looking into several classifications of food and would be interested in sharing what we are using when the time comes. We will want to know when to switch from ENVO to the new ontology. If the foods will have roles, being allergenic may be a useful one to have. Should I switch to the ENVO term tracker?
-Randi

**Comment by pbuttigieg** [comment]
>Because of the food allergic diseases, we have been looking into several classifications of food and would be interested in sharing what we are using when the time comes.

This overlaps with our current (nascent) efforts. It would be good to syncronise!

> If the foods will have roles, being allergenic may be a useful one to have. 

Yes, absolutely. 

> Should I switch to the ENVO term tracker?

Probably best, I've created an issue here: https://github.com/EnvironmentOntology/envo/issues/284

**Comment by cooperl09** [comment]
Hi Randi,
Thanks for your interest in the Plant Ontology.  I have been following this discussion with interest, especially about the development of a food ontology.  
Here are comments on your questions: 
1) fruit PO_0009001: for this term, nut and grain are synonyms. We want to logically define fruit, nut and grain allergies as separate diseases based upon the allergy being to a different PO term. Is it possible to split the term or make more specific child terms?

*This is something we have discussed and it is a possibility- I also think it would be useful.  I suggest you open a separate issue on this tracker.*

2) vegetable: this term does not exist in PO, but we want to logically define vegetable allergy as a disease. Is this term something that PO could add?

*This is a bit problematic for the PO, as it is more of a grouping term than an actual plant structure. So I think it would better in the food ontology.  It is generally defined as any edible part of a plant, that is not involved in reproduction.* 

3) legume: this term does not exist in PO, but we want to logically define a legume allergy. Is this term something that PO could add?
*This is a taxonomic classification- we would reference it using the NCBI Taxonomy ID: 3803.*

4) cereal and pseudocereal: these are terms used to group foods allergens, but I am not sure if they have any basis in botany? Do you think they are reasonable terms or should we try different terms?
thanks very much. we appreciate your ontology! 

*In the PO we would call a cereal grain a "caryopsis" while the pseudocereals are actually seeds so they are botanically distinct.*
I hope this was helpful!
Laurel
