### ISSUE TITLE
Incorporation of Spine Roots in the PO

### ISSUE THREAD

**Issue by btsinn** [Planteome/plant-ontology#632]
We have been looking into a morphological phenomenon that does not seem to accommodated in the PO. In some groups of plants (especially in Palms) the roots can become highly sclerified and function as defensive spines. These structures are derived from adventitious roots in all cases that we are aware of. I have attached two articles documenting what I am describing. 

Plate 1 of the attached Chandler paper shows an _Acanthorhiza_ palm with roots that have emerged throughout the trunk and become highly sclerified– these roots are extremely similar to the prop roots but never reach the soil. 

The Hill paper describes the roots of _Dioscorea prehensilis_, a case where only the lateral portions of roots become sclerified. We propose that two new terms are added to the PO

1) spine root or root spine as a subclass of shoot-borne root 

2) Lateral Root Spine or Lateral Spine Root as a subclass of lateral root. 

Thanks so much for your feedback!

[Chandler - 1909 - Aerial Roots of Acanthorhiza aculeata.pdf](https://github.com/Planteome/plant-ontology/files/511137/Chandler.-.1909.-.Aerial.Roots.of.Acanthorhiza.aculeata.pdf)

[Hill - 1903 - The Root Structure of Dioscorea prehensilis.pdf](https://github.com/Planteome/plant-ontology/files/511138/Hill.-.1903.-.The.Root.Structure.of.Dioscorea.prehensilis.pdf)

**Comment by btsinn** [comment]
1) Proposed definition for Spine Shoot-borne Root (I think that this is probably preferable over Spine Root): A shoot-borne root (PO:0000042) that is sclerified and pointed.

**Comment by btsinn** [comment]
2) Proposed definition for Spine Lateral Root: Spine Lateral Root – A lateral root (PO:0020121) that is sclerified and pointed.

**Comment by cooperl09** [comment]
Propose slightly revised name and def'n: 
shoot-borne root spine (PO:new) : A shoot-borne root (PO:0000042) that is sclerified and pointed, grows determinately and lacks nutritive function.

Note: we should review def'n of root (PO:0009005) #578

**Comment by btsinn** [comment]
I agree that it seems more intuitive, for English at least, that spine is at the end of the name. I also agree with the augmented definition, but think that the "grows determinately" should be moved to the comments portion and is qualified with a "usually."

**Comment by btsinn** [comment]
Added shoot-borne root spine (PO:0030089): A shoot-borne root (PO:0000042) that is sclerified, pointed, and lacks indeterminate growth and nutritive function.

**Comment by btsinn** [comment]
Added lateral root spine (PO:0030088): A lateral root (PO:0020121) that is sclerified, pointed, and lacks indeterminate growth and nutritive function.
