### ISSUE TITLE
lenticel (PO:0000031)

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/plant-ontology#633]
lenticel is defined as: part of 'shoot axis'. 
Sweet potato have lenticels. 
Could you make the term more generic so it could apply to sweet potato too?

**Comment by cooperl09** [comment]
Do we want to have separate terms for shoot axis lenticel and root lenticel?

**Comment by DarioJCavaliere** [comment]
Propose revised parent and def'n for lenticel (PO:0000031): A portion of the shoot axes periderm (PO:0005048) produced by the cork cambium (PO:0005599) and is distinguished by having phellem (PO:0004003) and phelloderm (PO:0005050) with intercellular spaces.

**Comment by cooperl09** [comment]
Propose slightly revised def'n:
lenticel (PO:0000031): A portion of the shoot axis periderm (PO:0005048) characterized by the presence of intercellular spaces between the cells of the phellem (PO:0004003) and phelloderm (PO:0005050) 
maybe put in comment?   produced by the cork cambium (PO:0005599)

**Comment by btsinn** [comment]
The definition of Lenticel (PO:0000031) has been updated to: A portion of the shoot axis periderm (PO:0005048) characterized by the presence of intercellular spaces between the cells of the phellem (PO:0004003) and phelloderm (PO:0005050). The comment is now: Lenticels are produced by the cork cambium and facilitate gas exchange.

**Comment by cooperl09** [comment]
Based on information about pneumatophore (PO:0025357) #653, propose moving lenticel to be is_a portion of periderm tissue, rather than a portion of shoot axis periderm tissue.  Pneumatophores are lateral roots with lenticels that act in gas exchange.  See #653 for revisions to pneumatophore.

**Comment by btsinn** [comment]
Lenticel (PO:0000031) has now been moved to is_a portion of periderm tissue, replacing the previous is_a portion of shoot axis tissue relationship.

**Comment by cooperl09** [comment]
Revised Def'n: 
lenticel (PO:0000031): A portion of periderm tissue (PO:0005046) characterized by the presence of intercellular spaces between the cells of the phellem (PO:0004003) and phelloderm (PO:0005050).
