### ISSUE TITLE
New term: root periderm scar

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#635]
While linking the PO and sweet potato ontology we noticed a possible issue with the term lenticel, it seems this term does not accurately describe the structures on sweet potato tubers. #633 
Lenticels are developed in the cortex and arise beneath stomata. They may form prior to the termination of primary growth before the periderm is initiated, or after the termination of primary growth (Evert, 2006). 

Lenticel-like structures on sweet potato tubers, among other agriculturally important roots like parsnips and carrots, are not formed in relation to stomata. In sweet potatoes, lateral roots emerge from deeply lobed roots (tubers), in rows along longitudinal grooves (Hayward, 1938). Damage to these lateral roots initiate a wound response that results in lenticel-like structures on sweet potato tubers. After lateral roots are injured, starch begins to disappear from the peripheral cell layers, excluding the outermost layer of injured cells. Next, cell proliferation begins in the starch free-zones of the periderm, parallel to the cut surface. Gradually a continuous layer is formed over the cut surface below the suberin deposit, which functions as a cork cambium and continues to divide to give rise to a layer of wound periderm. (Artschwager, 1931). 

We propose a new term be added to the PO, root wound periderm. 
root wound periderm: A portion of root periderm (PO:0005047) formed in response to injury.

http://www.openisbn.com/isbn/0471738433/
http://journals.lww.com/soilsci/citation/1939/10000/the_structure_of_economic_plants.33.aspx
[Artschwager Sweet Potato.pdf](https://github.com/Planteome/plant-ontology/files/527834/Artschwager.Sweet.Potato.pdf)

**Comment by cooperl09** [comment]
Propose slight modification to the name and def'n for this structure:  
root periderm scar (PO:new):  A portion of root periderm (PO:0005047) formed in response to an injury or the emergence of a lateral root (PO:0020121).

I think 'scar' is better than 'wound' to encompass the case where it is a lateral root scar.

**Comment by DarioJCavaliere** [comment]
Propose slight modification to the name and def'n for this structure:

root periderm scar (PO:new): A portion of root periderm (PO:0005047) formed in response to a disruption of the root epidermis (PO:0006036).

Comment: Lenticel-like structures on sweet potato tubers, among other agriculturally important roots like parsnips and carrots, that are not formed in relation to stomata. In sweet potatoes, lateral roots emerge from deeply lobed roots (tubers), in rows along longitudinal grooves resulting in a disruption of the root epidermis. Disruption caused by the emergence of lateral roots initiates a wound response that results in the production of root periderm scar tissue.

**Comment by btsinn** [comment]
root periderm scar (PO:0030090) has been added. 

Definition: A portion of root periderm (PO:0005047) formed in response to a disruption of the root epidermis (PO:0006036).

Comment: Root periderm scars are lenticel-like structures on the tuberous roots (PO:0025523) and tuberous root tuber (PO:0025476) of sweet potato, parsnips, and carrots. Disruption of the epidermis by the emergence of a lateral root initiates a wound response that results in the production of a root periderm scar. Gas exchange does not occur through a root periderm scar.

**Comment by cooperl09** [comment]
Suggest slight modification to the comment:
Root periderm scars are lenticel-like structures on the tuberous roots (PO:0025523) and tuberous root tuber**s** (PO:0025476) of **plants such as** sweet potato, and **cassava**. Disruption of the epidermis by the emergence of a lateral root initiates a wound response that results in the production of a root periderm scar. Gas exchange does not occur through a root periderm scar.

I suggest replacing the parsnip and carrot example with cassava.   Aren't parsnips and carrot not an enlarged tap root?  I don't believe they develops from a tuberous root, which usually develops from a shoot-borne root (PO:0000042) or a lateral root (PO:0020121).

**Comment by cooperl09** [comment]
Also, need to add synonym 'root lenticel'

**Comment by DarioJCavaliere** [comment]
Suggest slight modification to the comment:
Root periderm scars are lenticel-like structures on the tuberous roots (PO:0025523), **primary roots (PO:0020127)**, and/or tuberous root tubers (PO:0025476) of plants such as sweet potato, cassava, **parsnips, and carrots**. Disruption of the epidermis by the emergence of a lateral root initiates a wound response which results in the production of a root periderm scar. Gas exchange does not occur through a root periderm scar.

We suggest adding primary root (PO:0020127) to the comment to accommodate the inclusion of parsnips and carrots, which are neither lateral roots (PO:0020121) nor are they shoot-borne roots (PO:0000042), but do bear root periderm scars.

**Comment by cooperl09** [comment]
Sounds good!

**Comment by btsinn** [comment]
The comment for root periderm scar (PO:0030090) has been revised. It now reads:

Comment: Root periderm scars are lenticel-like structures on the tuberous roots (PO:0025523), primary roots (PO:0020127), and/or tuberous root tubers (PO:0025476) of plants such as sweet potato, cassava, parsnips, and carrots. Disruption of the epidermis by the emergence of a lateral root initiates a wound response which results in the production of a root periderm scar. Gas exchange does not occur through a root periderm scar.
