### ISSUE TITLE
carpel abaxial epidermis

### ISSUE THREAD

**Issue by tberardini** [Planteome/plant-ontology#639]
Like sepal abaxial epidermis:
http://browser.planteome.org/amigo/term/PO:0006054

is_a carpel epidermis,     PO:0025096
A portion of carpel epidermis that covers the abaxial/lower surface of a sepal. 
PMID:25788175

**Comment by cooperl09** [comment]
Just to clarification-
You are requesting a new term: 'carpel abaxial epidermis'
proposed def'n:  "A portion of carpel epidermis that covers the abaxial/lower surface of a sepal. " 
 is this a typo?
did you mean to say :
"A portion of carpel epidermis that covers the abaxial/lower surface of a **carpel**. "

I think in the case of a carpel, we would not use the word "lower" but just refer to it as the abaxial surface (away from the axis).

**Comment by tberardini** [comment]
Yes, typo.  :)  Incomplete editing of copy/paste of the analogous sepal term.

**Comment by cooperl09** [comment]
Added 2 new terms- figured it made sense to add them both at once.

carpel abaxial epidermis (PO:0025617) - A portion of carpel epidermis (PO:0025096) that covers the abaxial surface of a carpel (PO:0009030)." [PMID:25788175, PO:cooperl]
comment: The abaxial surface is the one which is furthest from the plant axis.
xref: PO_GIT:639
is_a: PO:0025096 ! carpel epidermis

carpel adaxial epidermis (PO:0025618): A portion of carpel epidermis (PO:0025096) that covers the adaxial surface of a carpel (PO:0009030)." [PO:cooperl]
comment: The adaxial surface is the one which is closest to the plant axis.
xref: PO_GIT:639
is_a: PO:0025096 ! carpel epidermis

**Comment by tberardini** [comment]
Thanks, Laurel!  When will this be live?

**Comment by cooperl09** [comment]
They are up on dev.planteome this morning.  The next full release will be in December.

**Comment by tberardini** [comment]
Great!  Thanks.
