### ISSUE TITLE
capsule fruit (PO:0030091) and subclasses

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#642]
capsule (PO:0030091)

Proposed def'n:
A fruit derived from a gynoecium (PO:0009062) with a dry pericarp (PO:0009084) which dehisces at maturity. 

Proposed Comment: 
Capsules (PO:new) are divided into subcategories depending upon the location of sutures in the pericarp that the seeds are released through. 

Synonym: none

see fruit #76

**Comment by DarioJCavaliere** [comment]
loculicidal capsule:  

A capsule (PO:new) which dehisces through the fruit locules (PO:0025270).

Comment: Species whose fruit serve as examples of this fruit type include: _Gossypium raimondii_ (cotton), _Hibiscus syriacus_ (rose of sharon or rose mallow).

**Comment by DarioJCavaliere** [comment]
septicidal capsule:  

A capsule (PO:new) which dehisces through the fruit septa (PO:0025268).

Synonym: septifragal capsule (exact)

Comment: Species whose fruit serve as examples of this fruit type include: _Aristolochia elegans_ (dutchman's pipe), _Populus trichocarpa_ (black cottonwood).

**Comment by DarioJCavaliere** [comment]
coccarium:  

A capsule (PO:new) which dehisces through the fruit septa (PO:0025268) and the fruit locules (PO:0025270).

Comment: Species whose fruit serve as examples of this fruit type include: _Jatropha curcas_ (physic nut) and _Manihot brachyloba_.

**Comment by DarioJCavaliere** [comment]
poricidal capsule:  

A capsule (PO:new) which dehisces through pores on the pericarp (PO:0009084). 

Synonym: none

Comment: Species whose fruit serve as examples of this fruit type include: _Papaver_ sp. (poppy).

**Comment by DarioJCavaliere** [comment]
circumscissile capsule: 

A capsule (PO:new) which dehisces through the release of a fruit operculum (PO:0025298). 

Synonyms: diplotegia, diplotegium, pyxides, pyxidium, pyxis 

Comment: Species whose fruit serve as examples of this fruit type include: _Eucalyptus grandis_ (rose gum).

**Comment by DarioJCavaliere** [comment]
urticle: 

A circumscissile capsule with one seed (PO:0009010) that is not attached to the pericarp (PO:0009084).
 
Synonym: none

Comment: Species whose fruit serve as examples of this fruit type include: _Amaranthus retroflexus_ (Amaranthaceae).

**Comment by DarioJCavaliere** [comment]
Revised capsule to capsule fruit (PO:0030091)

Previous def'n:
A fruit derived from a gynoecium (PO:0009062) with a dry pericarp (PO:0009084) which dehisces at maturity.

Revised def'n:
A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086), and dehisces at maturity.

Previous comment:
Capsules (PO:new) are divided into subcategories depending upon the location of sutures in the pericarp that the seeds are released through.

Revised comment:
Capsule fruits are divided into subcategories depending upon the location of sutures in the pericarp that the seeds are released through. 

Previous synonyms:
none

Revised synonyms:
capsule (exact), kapsel (exact, German), cápsula (exact, Spanish)

**Comment by btsinn** [comment]
Closing issue for capsule fruit (PO:0030091) and subclasses: 

**_capsule fruit (PO:0030091)_**

def'n: A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that usually dehisce. 

comment: Capsule fruits (PO:0030091) are divided into subcategories depending upon the location of sutures in the pericarp (PO:0009084) that the seeds (PO:0009010) are released through.

synonyms: capsule (exact), c�psula (exact, Spanish), kapsel (exact, German), dehiscent fruit (broad), indehiscent fruit (broad)

_**circumscissile capsule fruit (PO:0030096)**_

def'n: A capsule fruit (PO:0030091) which at maturity dehisces through the release of a fruit operculum (PO:0025298).

comment: Example: rose gum (Eucalyptus grandis).

synonyms: circumscissile capsule (exact), c�psula circuncisa (exact, Spanish), deckelkapsel (exact, German), pyxis (exact), diplotegia (narrow), dehiscent fruit (broad), pyxidium (broad)

_**utricle capsule fruit (PO:0030097)**_

def'n: A circumscissile capsule fruit (PO:0030096) which at maturity contains one seed (PO:0009010) that is not attached to a pericarp (PO:0009084).

comment: Example: common amaranth (Amaranthus retroflexus).

synonyms: hauptfrucht (exact, German), utricle (exact), utr�culo (exact, Spanish), dehiscent fruit (broad)

_**coccarium capsule fruit (PO:0030094)**_

def'n: A capsule fruit (PO:0030091) which at maturity dehisces through both the fruit septa (PO:0025268) and the fruit locules (PO:0025270).

comment: When annotating to a capsule fruit (PO:0030091) which only dehisces through the fruit septa (PO:0025268), annotate to septicidal capsule fruit (PO:0030093). When annotating to a capsule fruit which only dehisces through the fruit locules (PO:0025270), annotate to loculicidal capsule fruit (PO:0030092). Examples: physic nut (Jatropha curcas) and Manihot brachyloba.

synonyms: coccarium (exact), c�psula bicida (exact, Spanish), lokulizide-septifrage kapsule (exact, German), dehiscent fruit (broad)

_**loculicidal capsule fruit (PO:0030092)**_

def'n: A capsule fruit (PO:0030091) which at maturity dehisces through fruit locules (PO:0025270).

comment: When annotating to a capsule fruit (PO:0030091) which dehisces through both the fruit septa (PO:0025268) and fruit locules (PO:0025270), annotate to coccarium capsule fruit (PO:0030094). When annotating to a capsule fruit which only dehisces through the fruit septa, annotate to septicidal capsule fruit (PO:0030093). Examples: cotton (Gossypium raimondii) and rose mallow (Hibiscus syriacus).

synonyms: c�psula loculicida (exact, Spanish), loculicidal capsule (exact), lokulizide kapsule (exact, German), dehiscent fruit (broad)

_**poricidal capsule fruit (PO:0030095)**_

def'n: A capsule fruit (PO:0030091) which at maturity dehisces through pores on a pericarp (PO:0009084).

comment: Example: poppy (Papaver spp.).

synonym: c�psula por�fera (exact, Spanish), porenkapsel (exact, German), poricidal capsule (exact), dehiscent fruit (broad)

_**septicidal capsule fruit (PO:0030093)**_

def'n: A capsule fruit (PO:0030091) which dehisces through a fruit septa (PO:0025268). 

comment: When annotating to a capsule fruit (PO:0030091) which dehisces through both the fruit septa (PO:0025268) and fruit locules (PO:0025270), annotate to coccarium capsule fruit (PO:0030094). When annotating to a capsule fruit which only dehisces through the fruit locules, annotate to loculicidal capsule fruit (PO:0030092). Examples: dutchman's pipe (Aristolochia elegans) and black cottonwood (Populus trichocarpa).

synonyms: c�psula septicida (exact, Spanish), c�psula sept�fraga (exact, Spanish), septicidal capsule (exact), septifragal capsule (exact), septizide kapsel (exact, German), dehiscent fruit (broad)
