### ISSUE TITLE
samara fruit (PO:0030099)

### ISSUE THREAD

**Issue by btsinn** [Planteome/plant-ontology#644]
samara (PO:0030099)

Proposed def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) with dry, wing-shaped pericarp (PO:0009084) which does not split at maturity.

Proposed comment: 
Species whose fruit serve as examples of this fruit type include: _Fraxinus pennsylvanicum_ (green ash) and _Ailanthus altissima_ (tree of heaven).

see fruit #76

**Comment by DarioJCavaliere** [comment]
fruit #76

**Comment by DarioJCavaliere** [comment]
Revised samara to samara fruit (PO:0030099)

Previous def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) with dry, wing-shaped pericarp (PO:0009084) which does not split at maturity.

Revised def'n:
A fruit (PO:0009001) which develops from a carpel (PO:0009030) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are elongated into a wing. 

Previous comment:
Species whose fruit serve as examples of this fruit type include: Fraxinus pennsylvanicum (green ash) and Ailanthus altissima (tree of heaven).

Revised comment:
The pericarp can be expanded laterally or radially. Examples: green ash (Fraxinus pennsylvanicum) and tree of heaven (Ailanthus altissima).

Revised synonyms:
flügfrucht (exact, German), sámara (exact, Spanish), samara (exact)

**Comment by DarioJCavaliere** [comment]
Closing issue for samara fruit (PO:0030099):

def'n: A fruit (PO:0009001) which develops from a carpel (PO:0009030) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are elongated into a wing-like structure. 

comment: The pericarp (PO:0009084) can be expanded laterally or radially. The wing-shaped fruits of maples (Acer spp.) are often mistakenly identified as samara fruits (PO:0030099), but are instead schizocarp fruits (PO:0030098) with samaroid mericarps (PO:0020075). Examples: green ash (Fraxinus pennsylvanicum) and tree-of-heaven (Ailanthus altissima).

synonyms: fl�gfrucht (exact, German), samara (exact), s�mara (exact, Spanish), indehiscent fruit (broad)
