### ISSUE TITLE
legume fruit (PO:0030100)

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#645]
legume (PO:0030100)

Proposed def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) and has a dry pericarp (PO:0009084) which dehisces along two fruit valves (PO:0000033). 

Proposed Comment: 
Species whose fruit serve as examples of this fruit type include: members of Fabaceae, _Cajanus cajan_ (pigeon pea), _Cicer arietinum_ (chickpea), _Lens culinaris_ subsp. _Culinaris_ (Lentils).

Synonym: pod (broad)

**Comment by DarioJCavaliere** [comment]
loment: 

A legume which is constricted between each seed (PO:0009010). 

Synonym: lomentum (exact)

Comment: Species whose fruit serve as examples of this fruit type include: members of Fabaceae, _Glycine max_ (soybean).

**Comment by DarioJCavaliere** [comment]
#76

**Comment by DarioJCavaliere** [comment]
#76

**Comment by DarioJCavaliere** [comment]
Fruit #76

**Comment by cooperl09** [comment]
Comments from @jaiswalp:
- Suggest renaming to "legume pod"
- add comment about peanut spp. - not a nut

**Comment by DarioJCavaliere** [comment]
Revised legume to legume fruit (PO:0030100)

Previous def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) and has a dry pericarp (PO:0009084) which dehisces along two fruit valves (PO:0000033).

Revised def'n:
A fruit (PO:0009001) which develops from a single carpel (PO:0009030) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) which dehisce along two fruit valves (PO:0000033) at maturity

Previous comment:
Species whose fruit serve as examples of this fruit type include: members of Fabaceae, Cajanus cajan (pigeon pea), Cicer arietinum (chickpea), Lens culinaris subsp. Culinaris (Lentils).

Revised comment:
Examples: members of Fabaceae, pigeon pea (Cajanus cajan), chickpea (Cicer arietinum), and lentils (Lens culinaris subsp. culinaris).

Previous synonyms:
pod (broad)

Revised synonyms:
hülse (exact, German), legumbre (exact, Spanish), pod (broad)

**Comment by DarioJCavaliere** [comment]
Revised loment to loment fruit (PO:0030101)

Previous def'n:
A legume which is constricted between each seed (PO:0009010).

Revised def'n:
A legume fruit (PO:0030100) which is constricted between each seed (PO:0009010). 

Previous comment:
Species whose fruit serve as examples of this fruit type include: members of Fabaceae, most notable is Glycine max (soybean).

Revised comment:
Examples: some members of Fabaceae, including soybean (Glycine max).

Previous synonyms:
pod (broad)

Revised synonyms:
gliederhülse (exact, German), lomento (exact, Spanish), lomentum (exact)

**Comment by btsinn** [comment]
Closing issue tracker for legume fruit (PO:0030100):

def'n: A fruit (PO:0009001) which develops from a carpel (PO:0009030) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that dehisce along two fruit valves (PO:0000033).

comment: Legume fruit (PO:0030100) is characteristic of the plant family Fabaceae. Examples: pigeon pea (Cajanus cajan), chickpea (Cicer arietinum), peanut (Arachis hypogaea), soybean (Glycine max), and lentil (Lens culinaris subsp. culinaris).

synonyms: h�lse (exact, German), legumbre (exact, Spanish), legume (exact), dehiscent fruit (broad), pod (broad)

**Comment by btsinn** [comment]
Closing issue tracker for loment fruit (PO:0030101)

def'n: A legume fruit (PO:0030100) which at maturity separates into indehiscent, one-seeded segments.

comment: The pericarp (PO:0009084) of some legume fruit (PO:0030100), such as peanuts, is constricted between each seed, but these constrictions are due to a lack of support of the pericarp (PO:0009084) in the space between the seeds (PO:0009010). Contrastingly, the constrictions in the pericarp of loment fruits (PO:0030101) are sclerified and contain regions where cell death leads to disarticulation of the fruit (PO:0009001). Examples: some members of Fabaceae, including Mimosa and Desmodium spp.

synonyms: gliederh�lse (exact, German), loment (exact), lomento (exact, Spanish), lomentum (exact), indehiscent fruit (broad)
