### ISSUE TITLE
nut fruit (PO:0030102)

### ISSUE THREAD

**Issue by btsinn** [Planteome/plant-ontology#646]
nut (PO:0030102):

Proposed def'n:
A fruit (PO:0009001) derived from a gynoecium (PO:0009062) with one seed (PO:0009010) surrounded by a hard pericarp (PO:0009084) at maturity. 

Proposed comment: 
Species whose fruit serve as examples of this fruit type include: _Carya illinoinensis_ (pecan), _Juglans regia_ (Walnut), _Pistacia vera_ (pistachio), _Nelumbo nucifera_ (lotus), and _Quercus shumardii_ (acorn). 

Proposed synonyms: 
acorn (narrow), glans (exact), glandes (exact), nutlet (exact)

see fruit #76

**Comment by DarioJCavaliere** [comment]
fruit #76

**Comment by DarioJCavaliere** [comment]
Revised nut to nut fruit (PO:0030102)

Previous def'n:
A fruit (PO:0009001) derived from a gynoecium (PO:0009062) with one seed (PO:0009010) surrounded by a hard pericarp (PO:0009084) at maturity.

Revised def'n:
A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are not fused to a seed coat (PO:0009088). 

Previous comment:
Species whose fruit serve as examples of this fruit type include: Carya illinoinensis (pecan), Juglans regia (Walnut), Pistacia vera (pistachio), Nelumbo nucifera (lotus), and Quercus shumardii (acorn).

Revised comment:
Example: pecan (Carya illinoinensis), walnut (Juglans regia), pistachio (Pistacia vera), lotus (Nelumbo nucifera), and acorn (Quercus spp.).

Previous synonyms:
acorn (narrow), glans (exact), glandes (exact), nutlet (exact)

Revised synonyms:
nuez (exact, Spanish), nuß (exact, German), acorn (narrow), glans (exact), glandes (exact), nutlet (narrow)

**Comment by btsinn** [comment]
Closing issue for nut fruit (PO:0030102): 

def'n: A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are not fused to a seed coat (PO:0009088). 

comment: The common names of some species do not accurately reflect their fruit type. For example, the fruit (PO:0009001) of the peanut plant is a legume fruit (PO:0030100) rather than a nut fruit (PO:0030102). Example: pecan (Carya illinoinensis), walnut (Juglans regia), pistachio (Pistacia vera), lotus (Nelumbo nucifera), and acorn (Quercus spp.).

synonyms: glandes (exact), glans (exact), nuez (exact, Spanish), nut (exact), nutlet (exact), nu� (exact, German), acorn (narrow), indehiscent fruit (broad)
