### ISSUE TITLE
drupe fruit (PO:0030103)

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#647]
drupe (PO:0030103)

Proposed def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) and is composed of one or more seeds (PO:0009010) surrounded by fleshy exocarp (PO:0009085) and mesocarp (PO:0009087), and a stony endocarp (PO:0009086). 

Proposed Comment: 
May develop from an inferior or superior syncarpous gynoecium (PO:0009062)(Simpson, 2010). Species whose fruit serve as examples of this fruit type include: _Amborella trichopoda_, _Coffea canephora_ (coffee), _Davidia_ spp. (Cornaceae), and _Prunus_ spp. (peach and plum).

Synonym: stone fruit (exact)

see Fruit #76

**Comment by cooperl09** [comment]
Comments from @jaiswalp:
- add comment about cashew- not a nut, but a drupe
- Suggest renaming to "drupe fruit"

**Comment by btsinn** [comment]
Revised drupe (PO:0030103) to drupe fruit

Previous def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) and is composed of one or more seeds (PO:0009010) surrounded by fleshy exocarp (PO:0009085) and mesocarp (PO:0009087), and a stony endocarp (PO:0009086).

Revised def'n: 
A fruit (PO:0009001) which develops from a carpel (PO:0009030), and comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and a stony endocarp (PO:0009086) with one or more seeds (PO:0009010).

Previous comment:
May develop from an inferior or superior syncarpous gynoecium (PO:0009062)(Simpson, 2010). Species whose fruit serve as examples of this fruit type include: Amborella trichopoda, Coffea canephora (coffee), Davidia spp. (Cornaceae), and Prunus spp. (peach and plum).

Revised comment:
May develop from an inferior or superior carpel (PO:0009030). Examples: Amborella trichopoda (a basal angiosperm), coffee (Coffea canephora), Cornaceae (including Davidia spp.), and peach and plum (Prunus spp.).

**Comment by DarioJCavaliere** [comment]
Closing issue for drupe fruit (PO:0030103):

def'n: A fruit (PO:0009001) which develops from a carpel (PO:0009030) and at maturity comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and a stony endocarp (PO:0009086). 

comment: May develop from an inferior or superior carpel (PO:0009030) and may contain one or more seeds (PO:0009010). Examples: Amborella trichopoda (basal angiosperm), coffee (Coffea canephora), Cornaceae (Davidia spp.), cashew (Anacardium occidentale), coconut (Cocos nucifera), and almond, peach and plum (Prunus spp.).

synonyms: drupa (exact, Spanish), drupe (exact), steinfrucht (exact, German), stone fruit (exact), indehiscent fruit (broad)
