### ISSUE TITLE
caryopsis fruit (PO:0030104)

### ISSUE THREAD

**Issue by btsinn** [Planteome/plant-ontology#648]
caryopsis (PO:0030104) 

Proposed def'n:
A fruit (PO:0009001) where the seed coat (PO:0009088) is fused to the dry pericarp (PO:0009084) which does not split at maturity.

Proposed comment: 
Species whose fruit serve as examples of this fruit type include: _Aegilops tauschii_ (Tausch’s goatgrass), _Brachypodium distachyon_ (stiff brome), _Hordeum vulgare_ (barley), _Leersia perrieri_ (cutgrass),  _Oryza australiensis_ (rice), _Oryza eichingeri_ (rice), _Oryza longistaminata_ (rice), _Oryza officinalis_ (rice), _Oryza rufipogon_ (rice), _Oryza sativa_ (rice), _Setaria italica_ (foxtail millet),  _Sorghum bicolor_ (sorghum), _Triticum aestivum_ (common wheat), _Triticum monococcum_ (einkorn wheat), _Triticum turgidum_ (rivet wheat), _Triticum urartu_ (red wild einkorn), and _Zea mays_ (corn).

Proposed synonyms: 
caryopsides (exact), grain (exact), kernel (exact)

see fruit #76

**Comment by cooperl09** [comment]
Comments from @jaiswalp:
1. Suggest renaming to "caryopsis fruit"
2. grain and kernel should be broad synonyms

**Comment by DarioJCavaliere** [comment]
Revised caryopsis to caryopsis fruit (PO:0030104)

Previous def'n:
A fruit (PO:0009001) where the seed coat (PO:0009088) is fused to the dry pericarp (PO:0009084) which does not split at maturity.

Revised def'n:
A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are fused to a seed coat (PO:0009088). 

Previous comment:
Species whose fruit serve as examples of this fruit type include: Aegilops tauschii (Tausch’s goatgrass), Brachypodium distachyon (stiff brome), Hordeum vulgare (barley), Leersia perrieri (cutgrass), Oryza australiensis (rice), Oryza eichingeri (rice), Oryza longistaminata (rice), Oryza officinalis (rice), Oryza rufipogon (rice), Oryza sativa (rice), Setaria italica (foxtail millet), Sorghum bicolor (sorghum), Triticum aestivum (common wheat), Triticum monococcum (einkorn wheat), Triticum turgidum (rivet wheat), Triticum urartu (red wild einkorn), and Zea mays (corn).

Revised comment:
Examples: Tausch’s goatgrass (Aegilops tauschii), stiff brome (Brachypodium distachyon), barley (Hordeum vulgare), cutgrass (Leersia perrieri), rice (Oryza australiensis, O. eichingeri, O. longistaminata, O. officinalis, O. rufipogon, and O. sativa), foxtail millet (Setaria italica), sorghum (Sorghum bicolor), common wheat (Triticum aestivum), einkorn wheat (Triticum monococcum), rivet wheat (Triticum turgidum), red wild einkorn (Triticum urartu), and corn (Zea mays).

Previous synonyms:
caryopsides (exact), grain (exact), kernel (exact)

Revised synonyms:
caryopse (exact, German), cariopse (exact, Spanish), cariópside (exact, Spanish), caryopsides (exact), grain (narrow), kernel (narrow)

**Comment by btsinn** [comment]
Closing issue caryopsis fruit (PO:0030104):

def'n: A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are fused to a seed coat (PO:0009088).

comment: Caryopsis fruit (PO:0030104) is characteristic of the Poaceae (the grass family). Caryopsis fruits develop from a pseudomonomerous gyneocium (PO:0009062), and contain only a single seed due to the abortion of two of the three carpels (PO:0009030). The pericarp of caryopsis fruits of some bamboo species is somewhat fleshy at maturity and is fused to the seed coat; these fruits are referred to in the literature as bacoid caryopses. Examples: barley (Hordeum vulgare), rice (Oryza spp.), wheat (Triticum spp.), corn (Zea mays), sorghum (Sorghum bicolor), oat (Avena spp.), zebra grass (Miscanthus spp.), Tausch’s goatgrass (Aegilops tauschii), stiff brome (Brachypodium distachyon), cutgrass (Leersia perrieri), and foxtail millet (Setaria italica).

synonyms: brown rice (exact), cariopse (exact, Spanish), cariópside (exact, Spanish), caryopse (exact, German), caryopsides (exact), caryopsis (exact), cereal (exact), dehulled grain (exact), dehulled kernel (exact), grain (exact), kernel (exact), polished rice (exact), indehiscent fruit (broad)
