### ISSUE TITLE
silique fruit (PO:0030106)

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#650]
silique (PO:0030106)

Proposed def’n:
 A fruit (PO:0009001) derived from a gynoecium (PO:0009062), and has a dry pericarp (PO:0009084) dehiscing along two fruit valves (PO:0000033) separating from a persistent, parietal placentae (PO:0025078) and the fruit replum (PO:0025267). 

Proposed comment: 
Species whose fruit serve as examples of this fruit type include: members of Brassicaceae, _Arabidopsis lyrata_ (lyrate rockcress), _Arabidopsis thaliana_ (mouse-ear cress), _Brassica oleraceae_ (wild cabbage), _Brassica rapa_ (field mustard), _Capsella rubella_ (pink shepherd's purse). 

Synonyms: silicle (exact), siliqua (exact), silicula (exact)

fruit #76

**Comment by DarioJCavaliere** [comment]
Revised silique (PO:0030106) to silique fruit

Previous def'n:
A fruit (PO:0009001) derived from a gynoecium (PO:0009062), and has a dry pericarp (PO:0009084) dehiscing along two fruit valves (PO:0000033) separating from a persistent, parietal placentae (PO:0025078) and the fruit replum (PO:0025267).

Revised def'n:
A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086), that dehisce along two fruit valves (PO:0000033) that separate from a persistent fruit replum (PO:0025267) at maturity. 

Previous comment:
Species whose fruit serve as examples of this fruit type include: members of Brassicaceae, Arabidopsis lyrata (lyrate rockcress), Arabidopsis thaliana (mouse-ear cress), Brassica oleraceae (wild cabbage), Brassica rapa (field mustard), Capsella rubella (pink shepherd's purse).

Revised comment:
Examples: members of Brassicaceae, lyrate rockcress (Arabidopsis lyrata), mouse-ear cress (Arabidopsis thaliana), wild cabbage (Brassica oleracea), field mustard (Brassica rapa), and pink shepherd's purse (Capsella rubella).

Previous synonyms: 
silicle (exact), siliqua (exact), silicula (exact)

Revised synonyms: 
schote (exact, German), silicua (exact, Spanish), silícula (exact, Spanish), silicle (exact), siliqua (exact), silicula (exact), silique (exact)

**Comment by btsinn** [comment]
Closing issue for silique fruit (PO:0030107)

def'n: A fruit (PO:0009001) which develops from a gynoecium (PO:0009062) and at maturity comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086), that dehisce along two fruit valves (PO:0000033) and separate from a persistent fruit replum (PO:0025267). 

comment: In contrast to legume fruit (PO:0030100), silique fruit develop from a syncarpous (multicarpellate) gynoecium (PO:0009062) separated by a false septum (replum, PO:0025267), which persists through fruit maturity. Examples: members of Brassicaceae, lyrate rockcress (Arabidopsis lyrata), mouse-ear cress (Arabidopsis thaliana), wild cabbage (Brassica oleracea), field mustard (Brassica rapa), and pink shepherd's purse (Capsella rubella).

synonyms: schote (exact, German), silicle (exact), silicua (exact, Spanish), silicula (exact), siliqua (exact), silique (exact), sil�cula (exact, Spanish), dehiscent fruit (broad)
