### ISSUE TITLE
achene fruit (PO:0030107)

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#651]
achene (PO:0030107)

Proposed def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) and is composed of a single fruit locule (PO:0025270) and a single seed (PO:0009010), which is attached to the dry, indehiscent pericarp (PO:0009084) at a single point at maturity. 

Synonyms: akene (exact)

Fruit #76

**Comment by DarioJCavaliere** [comment]
Revised achene (PO:0030107) to achene fruit

Previous def'n:
A fruit (PO:0009001) derived from a single carpel (PO:0009030) and is composed of a single fruit locule (PO:0025270) and a single seed (PO:0009010), which is attached to the dry, indehiscent pericarp (PO:0009084) at a single point at maturity.

Revised def'n:
A fruit (PO:0009001) which develops from a carpel (PO:0009030) and comprises a dry exocarp (PO:0009085), dry mesocarp (PO:0009087), and dry endocarp (PO:0009086) that are fused to a seed coat (PO:0009088) at a single point.  

Revised comment:
Commonly referenced fruit types such as accessory or multiple fruits (comprised of accrescent receptacle or infructescence tissue) containing as parts achenes are here treated as achene. For example, when annotating for a gene involved in strawberry development, any gene of interest that is involved in the development of the receptacle tissue would be mapped to receptacle (PO:0009064); genes involved in sepal (PO:0009031) persistence or accrescence would map to sepal (PO:0009031), and those involved in fruit characteristics would be mapped to achene (PO:0030107). Examples: sunflower (Helianthus annuus), strawberry (Fragaria vesca), fig (Ficus carica), and marijuana (Cannabis sativa).

**Comment by btsinn** [comment]
Closing issue for achene fruit (PO:0030107)

def'n: A fruit (PO:0009001) which develops from a carpel (PO:0009030) or gyneocium (PO:0009062) and at maturity comprises a dry exocarp (PO:0009085), a dry mesocarp (PO:0009087), and a dry endocarp (PO:0009086) that are connected to a seed coat (PO:0009088) by a funicle (PO:0020006).

comment: Plant structures commonly referred to as ‘accessory’ (such as strawberry) or multiple fruits (such as figs..) which are comprised of accrescent receptacle (PO:0009064) or infructescence (PO:0006342) tissue, contain as parts achene fruits (PO:0030107). For example, when annotating for a gene involved in strawberry development, any gene of interest that is involved in the development of the receptacle tissue would be mapped to receptacle (PO:0009064); genes involved in sepal (PO:0009031) persistence or accrescence would map to sepal (PO:0009031), and those involved in fruit characteristics would be mapped to achene (PO:0030107). Examples: sunflower (Helianthus annuus), strawberry (Fragaria spp.), fig (Ficus sp.), and marijuana (Cannabis sativa).

synonyms: achene (exact), achäne (exact, German), akene (exact), aquenio (exact, Spanish), indehiscent fruit (broad)
