### ISSUE TITLE
berry fruit (PO:0030108) and subclasses

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#652]
berry (PO:0030108)

Proposed def'n:
A fruit (PO:0009001) which has a fleshy pericarp (PO:0009084) at maturity.

Proposed comment: 
Species whose fruit serve as examples of this fruit type include: _Capsicum annuum_ (peppers), _Carica papaya_ (papaya), _Malus domestica_ (apple), _Musa acuminata_ (banana), _Persea americana_ (avocado), _Podophyllum peltatum_ (may apple), _Phoenix dactylifera_ (date palm), _Solanum lycopersicum_ (tomato), _Solanum tuberosum_ (potato), _Theobroma cacao_ (chocolate), _Vaccinium_ spp. (blueberry), and _Vitis vinifera_ (grape).

Synonyms: bacca (exact), pome (narrow), and pepo (narrow)

fruit #76

**Comment by DarioJCavaliere** [comment]
hesperidium (PO: new)

Proposed def'n:
A berry (PO:new) derived from a gynoecium (PO:0009062) with exocarp (PO:0009085) and mesocarp (PO:0009087) of increased thickness and with juice sacs (PO:0006013) on the carpel adaxial epidermis (PO:0025618). 

Proposed comment: 
A hesperidium develops from a superior syncarpous gynoecium (PO:0009062). Species whose fruit serve as examples of this fruit type include: Citrus spp. (orange, grapefruit, lemon, and lime)

Synonym: citrus fruit (exact)

fruit #76

**Comment by cooperl09** [comment]
Comment from @jaiswalp: 
Prefer having pome and pepo as stand alone terms rather than narrow synonyms

**Comment by DarioJCavaliere** [comment]
We decided to subsume pepo and pome within berry, but keep hesperidium a stand-alone term. A hesperidium is the result of a superior gynoecium, while a pepo and a pome are the result of inferior gynoecium. This means a pepo and a pome are berries that are encapsulated in receptacle tissue. A hesperidium is not surrounded in receptacle tissue, and the outer layers of an orange are solely pericarp. Since we consider anything aside from pericarp layers to not be fruit, we have included hesperidium but not pepo or pome.

**Comment by jaiswalp** [comment]
by the definition I am reviewing for berry it says A fruit (PO:0009001) which has a fleshy pericarp (PO:0009084) at maturity. However there is no mention about the placement of ovary. Whereas by the statement.. .This means a pepo and a pome are berries that are encapsulated in receptacle tissue. we are indirectly saying that berries have inferior ovary. Is that right? If so we need a bit more reined definition for berry. On the other hand, as we expand the fruit subclasses, I suspect, if a squash/cucurbit family curator wants to curate, they might as well prefer a stand alone term 'pepo' and Rosaceae guys may want 'pome'. No harm having them as subclasses of berry as the definition suggests.

**Comment by DarioJCavaliere** [comment]
Yes, you are correct that pepo and pome are berries encapsulated in receptacle tissue, but that does not mean that all berries develop from inferior ovaries. A pepo and a pome are developed from inferior ovaries, which is why they are berries encapsulated in receptacle tissue. The position of the ovary probably does not need to be included in the definition, but to create a proper definition for pepo or pome we have to explain that the pericarp is surrounded by receptacle tissue and the location of that boundary is unclear. This would mean annotating to 'pome' or 'pepo' would include receptacle tissue, when the curator may only intend to annotate to the fruit, and therefore the pericarp.

**Comment by btsinn** [comment]
Pepo fruit (PO:0030111 -- newly created term):

Def'n:
A berry fruit (PO:0030108) which develops from an inferior carpel (PO:0009030) and comprises a thick, fleshy exocarp (PO:0009085), and has as parts fleshy mesocarp (PO:0009087) and fleshy endocarp (PO:0009086) layers that are indistinguishable from the surrounding receptacle (PO:0009064) tissue.

Synonyms: 
none

Comment: 
Examples: pumpkin (Cucurbita pepo), cucumber (Cucumis sativus), and watermelon (Citrullus lanatus).

**Comment by btsinn** [comment]
pome fruit (PO:0030110 -- newly created term):

Def'n:
A berry fruit (PO:0030108) which develops from an inferior gynoecium (PO:0009062) and comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and hardened endocarp (PO:0009086) and has as a part a fleshy hypanthium (PO:0009065).

Synonyms:
none

Comment:
Examples: Apples, crab apples, and pears (Malus spp. and Pyrus spp.)

**Comment by btsinn** [comment]
revision to berry (PO:0030108) -- changed to berry fruit

Previous def'n:
A fruit (PO:0009001) which has a fleshy pericarp (PO:0009084) at maturity.

Revised def'n:
A fruit (PO:0009001) which comprises a fleshy endocarp (PO:0009086), fleshy mesocarp (PO:0009087), and fleshy exocarp (PO:0009085) at maturity.


Synonyms:
 bacca (exact), pome (narrow), and pepo (narrow)

Previous comment:
Species whose fruit serve as examples of this fruit type include: Capsicum annuum (peppers), Carica papaya (papaya), Malus domestica (apple), Musa acuminata (banana), Persea americana (avocado), Podophyllum peltatum (may apple), Phoenix dactylifera (date palm), Solanum lycopersicum (tomato), Solanum tuberosum (potato), Theobroma cacao (chocolate), Vaccinium spp. (blueberry), and Vitis vinifera (grape).

Revised comment:
Examples: pepper (Capsicum annuum), papaya (Carica papaya), apple (Malus domestica), banana (Musa acuminata), avocado (Persea americana), may apple (Podophyllum peltatum), date palm (Phoenix dactylifera), tomato (Solanum lycopersicum), potato (Solanum tuberosum), chocolate (Theobroma cacao), blueberry (Vaccinium spp.), and grape (Vitis vinifera).

**Comment by DarioJCavaliere** [comment]
Revisions to pepo (PO:0030111)

Previous def'n:
A berry fruit (PO:0030108) which develops from an inferior carpel (PO:0009030) and comprises a thick, fleshy exocarp (PO:0009085), and has as parts fleshy mesocarp (PO:0009087) and fleshy endocarp (PO:0009086) layers that are indistinguishable from the surrounding receptacle (PO:0009064) tissue.

Revised def'n:
A berry fruit (PO:0030108) which develops from an inferior carpel (PO:0009030) and comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and fleshy endocarp (PO:0009086) and has as a part a hard receptacle (PO:0009064) which is indistinct from the exocarp (PO:0009085).

**Comment by DarioJCavaliere** [comment]
Revisions to pome fruit (PO:0030110)

Previous def'n:
A berry fruit (PO:0030108) which develops from an inferior gynoecium (PO:0009062) and comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and hardened endocarp (PO:0009086) and has as a part a fleshy hypanthium (PO:0009065). 

Revised def'n:
A berry fruit (PO:0030108) which develops from an inferior gynoecium (PO:0009062) and comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and hardened endocarp (PO:0009086) and has as a part a fleshy hypanthium (PO:0009065) which is indistinct from the exocarp (PO:0009085).

**Comment by DarioJCavaliere** [comment]
Revisions to hesperidium (PO:0030109) -- changed to hesperidium fruit

Previous def'n:
A berry (PO:0030108) derived from a gynoecium (PO:0009062) with exocarp (PO:0009085) and mesocarp (PO:0009087) of increased thickness and with juice sacs (PO:0006013) on the carpel adaxial epidermis (PO:0025618).

Revised def'n:
A berry fruit (PO:0030108) which develops from a superior gynoecium (PO:0009062) and comprises a thickened exocarp (PO:0009085), thickened mesocarp (PO:0009087), and endocarp (PO:0009086), and has as parts juice sacs (PO:0006013) on a carpel adaxial epidermis (PO:0025618).

Previous comment:
A hesperidium develops from a superior syncarpous gynoecium (PO:0009062). Species whose fruit serve as examples of this fruit type include: Citrus spp. (orange, grapefruit, lemon, and lime)

Revised comment:
Examples: orange, grapefruit, lemon, and lime (Citrus spp.).

Previous synonyms: citrus fruit (exact)

Revised synonyms: citrus fruit (exact), hesperidium (exact)

**Comment by DarioJCavaliere** [comment]
Closing issue tracker for berry fruit (PO:0030108):

def'n: A fruit (PO:0009001) which at maturity comprises a fleshy endocarp (PO:0009086), fleshy mesocarp (PO:0009087), and fleshy exocarp (PO:0009085).

comment: Examples: pepper (Capsicum annuum), papaya (Carica papaya), avocado (Persea americana), may apple (Podophyllum peltatum), date palm (Phoenix dactylifera), tomato (Solanum lycopersicum), potato (Solanum tuberosum), chocolate (Theobroma cacao), blueberry (Vaccinium spp.), and grape (Vitis vinifera).

synonyms: bacca (exact), baya (exact, Spanish), beere (exact, German), berry (exact), pyrine (narrow), indehiscent fruit (broad)

**Comment by DarioJCavaliere** [comment]
Closing issue tracker for hesperidium fruit (PO:0030109):

def'n: A berry fruit (PO:0030108) which develops from a superior gynoecium (PO:0009062) and at maturity comprises a thickened exocarp (PO:0009085), thickened mesocarp (PO:0009087), and endocarp (PO:0009086), and has as parts juice sacs (PO:0006013) on a carpel adaxial epidermis (PO:0025618). 

comment: A hesperidium fruit (PO:0030109) develops from a superior gynoecium (PO:0009062), and therefore is not surrounded by receptacle (PO:0009064) tissue. Examples: orange, grapefruit, lemon, and lime (Citrus spp.).

synonyms: citrus fruit (exact), hesperide (exact, German), hesperidio (exact, Spanish), hesperidium (exact), indehiscent fruit (broad), panzerbeere (broad, German)

**Comment by DarioJCavaliere** [comment]
Closing issue tracker for Pepo fruit (PO:0030111):

def'n: A berry fruit (PO:0030108) which develops from an inferior carpel (PO:0009030) and at maturity comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and fleshy endocarp (PO:0009086), and has as a part a hard receptacle (PO:0009064) which surrounds, and is indistinct from, the exocarp (PO:0009085).

comment: A pepo fruit (PO:0030111) is specialized type of berry fruit (PO:0030108) which is encapsuled by persistent, accrescent receptacle (PO:0009064) tissue. The rind, or tough outer covering, of pepo fruits comprises receptical tissue and at least the exocarp (PO:0009085) layer of the pericarp (PO:0009084). Examples: pumpkin (Cucurbita pepo), cucumber (Cucumis sativus), and watermelon (Citrullus lanatus) and banana (Musa acuminata).

synonyms: k�rbisfrucht (exact, German), pepo (exact), pep�nide (exact, Spanish), indehiscent fruit (broad), panzerbeere (broad, German) (broad)

**Comment by DarioJCavaliere** [comment]
Closing issue for pome fruit (PO:0030110):

def'n: A berry fruit (PO:0030108) which develops from an inferior gynoecium (PO:0009062) and at maturity comprises a fleshy exocarp (PO:0009085), fleshy mesocarp (PO:0009087), and hardened endocarp (PO:0009086) and has as a part a fleshy hypanthium (PO:0009065) which is indistinct from the exocarp (PO:0009085).

comment: A pome fruit (PO:0030110) is a specialized type of berry fruit (PO:0030108) which is encapsuled in persistent, accrescent receptacle (PO:0009064) and/or hypanthium (PO:0009065) tissue. Examples: Apple, crab apple, and pear (Malus spp. and Pyrus spp.)

synonyms: apfelfrucht (exact, German), kernfrucht (exact, German), kernobst (exact, German), pome (exact), pomo (exact, Spanish), indehiscent fruit (broad)
