### ISSUE TITLE
pneumatophore (PO:0025357)

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-ontology#653]
Need to modify the def'n and comment on pneumatophore (PO:0025357) now that we have revised lenticel (PO:0000031) #633- is_a portion of shoot axis periderm, so lenticels cannot occur on roots. 
But the new term root periderm scar (PO:0030090)  #635 is not involved in gas exchange. 
Do we need a new term for root axis lenticels? @DarioJCavaliere and @btsinn

Currently:
pneumatophore (PO:0025357):
Definition:  A lateral root that is erect and protrudes above the soil or water. 
Source: ISBN:9780881928501 
Comment:  Pneumatophores are found in trees that live in flooded habitats such as mangroves and often have many lenticels. May provide oxygen to below ground roots growing in flooded soils. Sometime prop roots (PO:0000044) may act as breathing roots. In that case, the annotation should go to PO:0000044, whereas this term should be used for breathing roots arising at or below the soil or water surface. Knee roots are a type of pneumatophore in which the lateral root first grows upward, then turns and grows back down into the substrate, forming a knee-like bend.

http://www.academia.edu/6206486/Structure_of_Lenticels_on_the_Pneumatophores_of_Avicennia_marina_as_Aerating_Device_Deliver_Oxygen_in_Mangrove_s_root

**Comment by btsinn** [comment]
Rather than create a root axis lenticel term, could we modify the relationship of lenticel such that they can develop from either root periderm (PO:0005047) or shoot axis periderm (PO:0005048)? From the paper that you share here, and the one I have attached, it looks as those the lenticels on the pneumatophores of _Avicennia_ develop from periderm layers, and facilitate gas exchange, which is consistent with our definition of lenticel (PO:0000031). 

[Purnobasuki_Suzuki_2005.pdf](https://github.com/Planteome/plant-ontology/files/622901/Purnobasuki_Suzuki_2005.pdf)

**Comment by cooperl09** [comment]
pneumatophore (PO:0025357)
Revised def'n and comment: 
was: "A lateral root that is erect and protrudes above the soil or water." 

Comment: Pneumatophores are found in trees that live in flooded habitats such as mangroves and often have many lenticels. May provide oxygen to below ground roots growing in flooded soils. Sometime prop roots (PO:0000044) may act as breathing roots. In that case, the annotation should go to PO:0000044, whereas this term should be used for breathing roots arising at or below the soil or water surface. Knee roots are a type of pneumatophore in which the lateral root first grows upward, then turns and grows back down into the substrate, forming a knee-like bend.

Revised def'n:  A lateral root (PO:0020121) that is erect and protrudes above the surface of the soil or water, and may provide oxygen to below-ground roots.

Revised Comment: 
Pneumatophores are found in trees that live in flooded habitats such as mangroves, and often have many lenticels (PO:0000031) which may provide oxygen to below-ground roots growing in flooded soils. Knee roots are a type of pneumatophore in which the lateral root first grows upward, then turns and grows back down into the substrate, forming a knee-like bend. Note that a pneumatophore differs from a prop root (PO:0000044), which is formed at a stem node above the ground, and grows downward into the soil.

**Comment by cooperl09** [comment]
Perhaps knee root should be a stand alone term, rather than a narrow synonym?
