### ISSUE TITLE
mericarp (PO:0020075)

### ISSUE THREAD

**Issue by DarioJCavaliere** [Planteome/plant-ontology#654]
Previous def'n:
One segment of a fruit of a schizocarp consisting of pericarp plus seed(s).

Revised def'n:
One carpellate unit of a schizocarp fruit (PO:0030098) consisting of pericarp (PO:0009084) and one or more seeds (PO:0009010).

Previous comment:
none

Revised comment:
Mericarps develop from a syncarpous gynoecium and the pericarp from each are fused together until maturity, at which point each carpellate unit separates from one another.  

![shizocarp](https://cloud.githubusercontent.com/assets/22643559/21196907/79ee4dac-c207-11e6-960b-980ca778f8a3.jpg)

see #643 and #76

**Comment by cooperl09** [comment]
Revisions to mericarp (PO:0020075), based on our discussion of 1-4-17

WAS:
mericarp (PO:0020075), One segment of a fruit of a schizocarp consisting of pericarp plus seed(s).

Revised: 
A cardinal part of multi-tissue plant structure (PO:0025498) which is one carpellate unit of a schizocarp fruit (PO:0030098) consisting of pericarp (PO:0009084) and one or more seeds (PO:0009010).

Previous comment: none

New comment:
A mericarp develops from one carpel of a syncarpous gynoecium. The pericarp of each carpel are fused together until maturity, at which point the carpellate units separate from one another.
