### ISSUE TITLE
petiole gland for Rosaceae spp.

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-ontology#658]
Need a PO term for the petiolar gland for the GDR traits.  

Is_a parent:  portion of secretory tissue  (PO:0005656)

Refer to references:
https://www.jstor.org/stable/pdf/2470152.pdf
http://michiganflora.net/genus.aspx?id=Prunus

**Comment by btsinn** [comment]
I can see the interest in such a PO term, but I wonder if a difference exists between these glands and other similar glands that occur on the serrations of many leaves in the Rosaceae (and other plant families), aside from position. In Prunus, some species have, for any single leaf, glands at the base of the petiole and glands at the apices of the serrations near the proximal end of the leaf blade.

**Comment by cooperl09** [comment]
Added as a narrow synonym of extrafloral nectary ( PO:0009057)- see  #659 
petiolar gland (narrow)
