### ISSUE TITLE
Rename: inflorescence branch meristem (PO:0009105) >> inflorescence axillary meristem (PO:0009105)

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-ontology#671]
Based on the revisions to 'higher order inflorescence axis' (was: inflorescence branch) (PO:0009081), we will need to revise this term.  
See notes on
[March 14th, 2017 Planteome Ontology Meeting](http://wiki.planteome.org/index.php/Mar_14th,_2017_Ontology_Working_Group_Meeting)
inflorescence branch meristem (PO:0009105)
Current def: An inflorescence meristem (PO:0009108) that gives rise to an inflorescence branch (PO:0009081).

See also history of this term on #437

**Comment by DarioJCavaliere** [comment]
inflorescence axillary meristem  (PO:0009105)

Renaming of: inflorescence branch meristem (PO:0009105)
	   	
Current def'n: An inflorescence meristem (PO:0009108) that gives rise to an inflorescence branch (PO:0009081).

Revised def’n: An inflorescence meristem (PO:0009108) that gives rise to a higher order inflorescence axis (PO:0009081).

Current comment: None.

Revised comment: No revisions.

Current synonyms: meristema lateral de la inflorescencia (Spanish, exact), 花序側部（側方）分裂組織 (Japanese, exact)

Revised synonyms: meristema lateral de la inflorescencia (Spanish, exact), 花序側部（側方）分裂組織 (Japanese, related)

**Comment by cooperl09** [comment]
Completed, closing
