### ISSUE TITLE
New term: pedicel (PO:0030112)

### ISSUE THREAD

**Issue by btsinn** [Planteome/plant-ontology#672]
Currently, the axis upon which a solitary flower develops is not treated in the PO. The same issue exists for the axis that supports a single fruit. The term for these axes is the pedicel, however pedicel is currently used in the PO only in reference to the ultimate axes of inflorescences or infructescences. 

We propose pedicel (PO:0030112) as a direct subclass of shoot axis. This new term has four direct subclasses: flower pedicel (PO:0030113; #673), inflorescence pedicel (PO:0009052, renaming of flower pedicel; #89), fruit pedicel (PO:0030114; #487), and infructescence pedicel (PO:0004536, renaming of fruit pedicel; #487).

-------------------------------------------------------------------------------------------------------------------

pedicel (PO:0030112)

Def'n: 
_A shoot axis that terminates in a flower (PO:0009046) or a fruit (PO:0009001)._

Comment: 
_All flowers and fruits terminate shoots called pedicels, although the highly reduced pedicels of sessile flowers and fruits can be rather inconspicuous. If possible, use the most specific subclass of pedicel available when mapping annotations to this term. The development of a flower or fruit at the apex of a pedicel means that all pedicels have a single internode, have determinate growth, and are the ultimate axes of a plant._ 

Synonyms:
_pedicelo (Spanish, broad)_

**Comment by cooperl09** [comment]
Revised comment: 
All pedicels have a single internode, have determinate growth, and are the ultimate axes of a plant.
When annotating to this term, use the most specific subclass of pedicel: flower pedicel (PO:0030113), inflorescence flower pedicel (PO:0009052), fruit pedicel (PO:0030114), or infructescence fruit pedicel (PO:0004536).

**Comment by btsinn** [comment]
Revised comment: 
A pedicel has a single internode, determinate growth, and is the ultimate axis of a plant. When annotating to this term, use the most specific subclass of pedicel: flower pedicel (PO:0030113), inflorescence flower pedicel (PO:0009052), fruit pedicel (PO:0030114), or infructescence fruit pedicel (PO:0004536).
