### ISSUE TITLE
Question about fruit part

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [Planteome/plant-ontology#679]
I'm helping to curate the food ontology FoodOn and finesse our models of basic food processing.  At moment we are wondering how best to describe cored fruit, for food products like canned apples where the core is removed.  What part(s) of plant is an apple core considered in terms of PO terms, and what part is the remaining fruity flesh?  If the apple has been peeled, what would the peel mainly consist of, botanically?
Thanks for the information!

**Comment by cooperl09** [comment]
Hi Damion, 
An apple is a type of fruit called a pome fruit (PO:0030110). The core, surrounding the seeds is a pericarp, consisting of a hardened endocarp (PO:0009086), and a fleshy mesocarp (PO:0009087), and exocarp (PO:0009085).  This part is usually not eaten by humans.
The apple flesh part we eat is actually the hypanthium (PO:0009065), (but some sources refer to it as a receptacle (PO:0009064)). 

The apple skin (peel) is the outer epidermis of the hypanthium (PO:0009065)/ receptacle (PO:0009064) tissue. 
Wikipedia has a half-decent diagram of it: https://en.wikipedia.org/wiki/Pome- note they refer to the outer fleshy part as "floral parts" which refers to the hypanthium (PO:0009065) and/or receptacle (PO:0009064). 

You can view pome fruit (PO:0030110) on our development browser: http://dev.planteome.org/amigo/term/PO:0030110

I hope this was helpful :-)

**Comment by Public-Health-Bioinformatics** [comment]
Thanks - I've plugged those terms into FoodOn now.  

Related question: is a legume husk an exocarp?  I'm onto shelled beans, peas etc.

**Comment by cooperl09** [comment]
Are you referring to the pod? 
The outer layer of a legume pod is an exocarp (PO:0009085), but the layers are fused together and dry at maturity, so might be better to call the pod a pericarp (PO:0009084). 

legume fruit PO:0030100: 
http://browser.planteome.org/amigo/term/PO:0030100

**Comment by Public-Health-Bioinformatics** [comment]
Yes, the pod.  Thanks!
