### ISSUE TITLE
New term: gametophore coma (PO:0028005)

### ISSUE THREAD

**Issue by annikalsmith** [Planteome/plant-ontology#682]
Adding a new term for the flagellate plants project:

Proposed name and definition--
gametophore coma (PO:0028005):
A collective plant organ structure (PO:0025007) which is a cluster of gametophore branches (PO:0030021) or non-vascular leaves (PO:0025075) at the top of the gametophore axis (PO:0030020), forming a tuft.

**Comment by cooperl09** [comment]
Term has been added, closing this tracker
