### ISSUE TITLE
Consider removing xrefs to GRO which is obsolete from PO

### ISSUE THREAD

**Issue by jonquet** [Planteome/plant-ontology#685]
We found 492 Xrefs to GRO
http://bioportal.bioontology.org/ontologies/GRO

Which is declared obsolete on OBO Foundry and the latest version in BioPortal does not use the same ID Scheme. Therefore, those 492 Xrefs inside PO seems useless as there are no more target to resolve them to. 

Any thoughts?
\CC @elcioabrahao

**Comment by cooperl09** [comment]
Hi Clement,
Indeed there are 492 GRO xrefs in the PO, but the link you provide above is not the correct GRO ontology.  That link leads to the Gene Regulation Ontology.....
The GRO Ids in the PO come from: 
https://bioportal.bioontology.org/ontologies/GRO-CPGA and https://bioportal.bioontology.org/ontologies/GRO-CPD. (The second part of the names were added at the request of Bioportal some time ago.)
These ontologies were the precursors of the PO today and the xrefs are there to provide continuity for our users.  There may still be data out there annotated with these ids.  In fact, I recently found out that Ensemble is still using these. 
For example, user who comes to the PO can search for  GRO:0007003- germination in maize and be connected to seed germination stage id: PO:0007057 term.
