### ISSUE TITLE
fruit parthood

### ISSUE THREAD

**Issue by ddooley** [Planteome/plant-ontology#690]
From past discussion leading up to 2017 (https://github.com/Planteome/plant-ontology/issues/76) I see the various subclasses of fruit put in place, e.g.
http://purl.obolibrary.org/obo/PO_0030110 hesperidium fruit
The english definitions talk about parts of fruit **at maturity**. I was wondering if there were any plans in PO to put 'has part' relations from fruits to the components mentioned in their definitions or is the at maturity clause holding that back?  In FoodOn, I'm grappling with whether to define reference to a fruit like pear, grapefruit, etc. as reference to the whole fruit, or to have a more loose term that may or may not include all the parts. E.g. if a biosample mentions "apple", it might be peeled, cored, etc.  If I say an 'apple' is a 'pome fruit' and then import PO axioms, PO parthood relations could yield unsatisfiable an axiom about the biosample stating "apple and fruit(peeled)". So if that is coming in the future, then I'll need to define "apple" differently in FoodOn, e.g. "apple 'derives from' some pome fruit".

Thanks for any presaging...

Damion

**Comment by cooperl09** [comment]
Currently, there are no definite plans to add those 'has part' relations, but we may consider it in the future.  As far as how FoodOn defines instances of a particular type of fruit (PO:0009001) depends on how you plan to use the term.  In general, I would recommend defining those instances like pear, grapefruit, or apple as the whole fruit and using the existing "apple food product" for the processed item.

**Comment by ddooley** [comment]
Ok, thanks for the input!
