### ISSUE TITLE
plant ovary adaxial epidermis (PO:0005024) & vary abaxial epidermis (PO:0005023)

### ISSUE THREAD

**Issue by BKKirchoff** [Planteome/plant-ontology#691]
The PO terms "plant ovary adaxial epidermis" (PO:0005024) and "plant ovary abaxial epidermis"(PO:0005023) use the words adaxial and abaxial in a very unusual way. The adaxial side of the ovary has traditionally been used to refer to the side of the ovary that backs on the inflorescence axis (in first order branching systems), and the abaxial side is the side that is adjacent to the subtending bract. In the current terms "adaxial" is used to refer to the central axis of the flower, a use that is almost completely unknown in plant anatomy. These terms would make much more sense if they were changed to be "plant ovary inner epidermis" (PO:0005024) and plant ovary outer epidermis" (PO:0005023). The revised terms would then more clearly refer to the epidermis that lines the locules (PO:0005024) and the epidermis that surrounds the ovary on the outside (PO:0005023).

**Comment by cooperl09** [comment]
"plant ovary adaxial epidermis" (PO:0005024) and "plant ovary abaxial epidermis"(PO:0005023)  have been renamed "plant ovary inner epidermis" (PO:0005024) and plant ovary outer epidermis"(PO:0005023).  The current names have been added as related synonyms. 
names have been corrected in related terms as well. The changes will be available on the Planteome Development browser (http://dev.planteome.org/amigo) tomorrow (reloads nightly) and on the live Planteome site (http://planteome.org/amigo) after the next db release, probably about mid-April 2019.
