### ISSUE TITLE
PO marks RO:'developmentally preceded by' as deprecated

### ISSUE THREAD

**Issue by balhoff** [Planteome/plant-ontology#693]
In PO, RO:0002258 [developmentally preceded by](http://purl.obolibrary.org/obo/RO_0002258) is marked as deprecated. However this isn't the case in RO. This is showing up in GO due to the PO import.

If it's not being used, could you delete the term in PO instead of adding this annotation?

**Comment by cooperl09** [comment]
I removed the ""is_obsolete: true" from 'id: developmentally_preceded_by" 
#401d05aa08b9f3ba8e1fa42076262334b0fa813b

**Comment by balhoff** [comment]
Thanks @cooperl09!
