### ISSUE TITLE
Adding material entities from plant parts

### ISSUE THREAD

**Issue by LilyAndres** [Planteome/plant-ontology#696]
Can PO add a new term for referring to a specific material entity for a plant part, for example, "**grain**" derived from "seed"? @ramonawalls @CropStoreDb

**Comment by cooperl09** [comment]
In theory, yes we could, but the example you provide makes no sense botanically.  A grain is a caryopsis fruit (http://browser.planteome.org/amigo/term/PO:0030104) and develops from a gynoecium.  A seed (PO:0009010) on the other hand develops from a plant ovule.  In other words, the grain is a special kind of fruit which contains a single seed.  Caryopses are specific to the Poaceae (the grass family). 

Also, we don't currently use the "derives_from" relation (http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/RO_0001000), but we use the more informative "develops_from", whihc would not be appropriate here.

**Comment by LilyAndres** [comment]
You are correct that for cereal 'grains' they are caryopses. However, in trade and common parlance the term legume 'grain' is also sometimes used, yet these are multiple seeds that develop from an ovule. So we have a difference in botanical and agricultural use of the term grain/seed,  For a harvested product the term 'develops_from' does not seem appropriate. For crop products, we are at the interface between botanical and commodity entities.

**Comment by ramonawalls** [comment]
I think we will be able to define these classes in FOODON, which is probably a better home after all. They are now importing PO terms, so we can use the derived from relations there. Thanks for the consideration, @cooperl09 !

**Comment by cooperl09** [comment]
Thanks to you both for he comments and discussion.  I am closing this issue.
