### ISSUE TITLE
how to do enrichment analysis like Gene ontology(GO)

### ISSUE THREAD

**Issue by shangguandong1996** [Planteome/plant-ontology#698]
Hi, Dear developer
I found plant-ontology(PO) is very useful for me, But I am wondering whether I can do enrichment analysis like GO. Can you recommend some pipline or case-study about PO enrichment analysis?

Best wishes
Guandong Shang

**Comment by cooperl09** [comment]
You can do an ontology enrichment query of the Planteome Database for a list of genes here: http://planteome.org/oat/
How well this works will depend upon the species selected, as the data has to be in the database. 
Please click on the "manual" button for more details on using the tool 
You can also do a filtered search for annotations at Planteome.org
The enrichment tool and visualizations are currently under development, so please feel free to provide feedback at: http://planteome.org/contact

**Comment by shangguandong1996** [comment]
Thanks for your reply :)
