### ISSUE TITLE
Does PO have something like "multiple fruit" or "fruit multiple"

### ISSUE THREAD

**Issue by ddooley** [Planteome/plant-ontology#699]
Like: [http://purl.obolibrary.org/obo/FLOPO_0016496](http://purl.obolibrary.org/obo/FLOPO_0016496)
or: [https://en.wikipedia.org/wiki/Multiple_fruit](https://en.wikipedia.org/wiki/Multiple_fruit)

**Comment by cooperl09** [comment]
Hi Damion, 
At the current time, the terms for multiple or aggregate fruits are synonyms of fruit: 
aggregate fruit (broad), compound fruit (broad), multiple fruit (broad).  
This is an area that would be good to expand on with more specific classes.

**Comment by ddooley** [comment]
Ok. In meantime we'll use FLOPO term.
