### ISSUE TITLE
anther and other classes being hard-coded as subclasses of "independent continuant"

### ISSUE THREAD

**Issue by ddooley** [Planteome/plant-ontology#700]
I'm seeing some multihoming that looks like it might be result of an accidental inclusion of a conversion of inferred axioms: 

![image](https://user-images.githubusercontent.com/4000582/94653578-a58e5400-02b0-11eb-8abd-6506c5c297ec.png)

I'm sure no one needed "anther" to be hardcoded as subclass of "independent continuant" ?!
There are similar hard-coded subclasses in other areas too in PO file now, e.g. under "continuant".

Can this be undone?

**Comment by cooperl09** [comment]
HI Damion,  Those relationship are not "hard-coded" per se, but are coming from the reasoner.  Which PO file are you using? 
If you look at the editors file: plant-ontology.obo you can see this.  Compare the asserted and Inferred views.
The version you are showing above also seems to be missing some of the subclass relationships.
![image](https://user-images.githubusercontent.com/7378000/94712283-20319080-02fe-11eb-91ea-4af50d0b41ea.png)
![image](https://user-images.githubusercontent.com/7378000/94712648-a1892300-02fe-11eb-9b6d-4682dc865339.png)

**Comment by phismith** [comment]
The appropriate BFO term should be 'material entity' -- or, for those items
which are separated by their own independent boundary, such as cells --
'object'
'Material entity' is safe in any case
BS

**Comment by ddooley** [comment]
Hmm, I just downloaded the po.owl file from github and did NOT run the reasoner.  The relations seem to be baked in, not inferred. This same view is being picked up by Ontobee (which I recall doesn't include inferred parenthood?).

**Comment by ddooley** [comment]
These hardcoded relations came into FoodOn when I imported PO terms via OntoFox, so that's what set me sleuthing.

**Comment by cooperl09** [comment]
Yes, Unfortunately those inferred relations appear to be converted into assertions in the release process. I will look into this a bit more.

**Comment by ddooley** [comment]
I guess I'd reiterate that the assertions, whether inferred or hard coded, seem to be at odd levels in the class structure.  Perhaps an artifact of earlier development cycle?  What I see in FoodOn as a result of PO import is:

![image](https://user-images.githubusercontent.com/4000582/111249331-c9c4bf80-85c8-11eb-8448-be62e397c171.png)

So bud, reproductive root system, shoot system etc. should be inferred lower down in class hierarchy, not up under continuant?

**Comment by cooperl09** [comment]
Hi Damion, This is indeed an artifact of the set up of the ontology and the effect of the reasoner during the release process.  We are doing some tests to determine the best way to address this.

**Comment by marieALaporte** [comment]
I believe this issue is fixed. The issues were probably caused by some domain/range constraints coming from RO. 
<img width="349" alt="Capture d’écran 2023-10-17 à 10 06 20" src="https://github.com/Planteome/plant-ontology/assets/5664149/1135a2ec-b2a3-4e09-b79d-ccfeafbecf52">

**Comment by ddooley** [comment]
Ok!
