### ISSUE TITLE
Representative term for underground parts of plant

### ISSUE THREAD

**Issue by Anoosha-Sehar** [Planteome/plant-ontology#701]
Hi, My name is Anoosha. I am a curator in Food Ontology (FoodOn) and working on investigating anatomical part of plant from which food is derived. Does PO has any term which could be used collectively for underground parts of plants i.e. for root/tuber/bulb?

**Comment by andru** [comment]
Just passing through and not involved or any authority on this project, but fyi you can find all of those terms in the plant anatomy ontology:

- root tuber: https://browser.planteome.org/amigo/term/PO:0025476
- bulb: https://browser.planteome.org/amigo/term/PO:0025356

If you enter your main search terms in https://browser.planteome.org/amigo/ and hit enter (ignore the search suggestions), click "ontology terms" on the next page, then in the left hand navigation click "ontology source" and click the green + by "plant_anatomy", that should get you a set of results you can work through to find the most relevant structure for your needs. 

Hope that's some help!

**Comment by cooperl09** [comment]
I replied to this a week ago, but for some reason, it has not shown up here:

**Comment by Anoosha-Sehar** [comment]
okay right, it's helpful to know. Thanks you very much!
