### ISSUE TITLE
New term request: meristem

### ISSUE THREAD

**Issue by kalpanaps** [Planteome/plant-ontology#708]
Description: A formative plant tissue usually made up of small cells capable of dividing indefinitely and giving rise to similar cells or to cells that differentiate to produce the definitive tissues and organs (BTO:0000852)

**Comment by cooperl09** [comment]
Meristems are already represented in the PO:

portion of meristem tissue (PO:0009013):  "A portion of plant tissue (PO:0009007) in which plant cells (PO:0009002) have retained their embryonic characteristics, or have reverted to them secondarily, and that divide to produce new cells that can undergo differentiation to form mature tissues, i.e. they have a capacity for morphogenesis and growth." [APweb:Glossary, Gramene:Pankaj_Jaiswal]
This term has 26 is_a children:
![image](https://user-images.githubusercontent.com/7378000/171219569-1ab39d59-73c1-44c5-b480-75723f3d53c5.png)
It is good practice to check the ontology before requesting terms.
