### ISSUE TITLE
plant ovary axiom reference to Magnoliophyta

### ISSUE THREAD

**Issue by ddooley** [Planteome/plant-ontology#713]
The PO import of http://purl.obolibrary.org/obo/NCBITaxon_3398, currently called Magnoliopsida in NCBITaxon, needs an update on the PO side. The PO label for it is currently Magnoliophyta (which is now listed as a synonym in NCBITaxon), and this is causing a duplicate label situation for FoodOn when it imports "plant ovary" term.

Thx!

**Comment by cooperl09** [comment]
Fixed in commit https://github.com/Planteome/plant-ontology/commit/602fcbf5e3d619a34d5e3df62c38cb719cd95a76
Thanks for bringing this to our attention
