### ISSUE TITLE
add PO identifiers for hash IRIs

### ISSUE THREAD

**Issue by balhoff** [Planteome/plant-ontology#714]
PO contains an object property `derives_by_manipulation_from` with IRI `http://purl.obolibrary.org/obo/po#derives_by_manipulation_from`, used in two axioms. These IRIs don't resolve and can't be turned into compact URIs using the normal PO prefix. I suggest immediately creating a PO ID for this relation, and also think about requesting the term for RO (then obsoleting the PO term).

There is another object property `http://purl.obolibrary.org/obo/po#isolated_from_germplasm` which is not used in any axioms. I would immediately obsolete this term, and re-add with a normal PO ID if it is needed later.

**Comment by matentzn** [comment]
I second this, thank you @balhoff for raising the issue across OBO. @cooperl09, can we help you address this? Would you be able to do so yourself?

**Comment by balhoff** [comment]
Thank you, @marieALaporte!

**Comment by cooperl09** [comment]
Yes, thanks @marieALaporte for your assistance!  I have merged the branch into the PO. These will be available in our next release.
