### ISSUE TITLE
relabel epidermis to plant epidermis

### ISSUE THREAD

**Issue by cmungall** [Planteome/plant-ontology#717]
there is already the precedent of naming terms to disambiguate, e.g. `plant cell`

can we also relabel `epidermis` so this doesn't cause confusion when looked at outside the context of plants?

**Comment by cooperl09** [comment]
Agreed, this makes sense.  Fixed in Commit https://github.com/Planteome/plant-ontology/commit/c99336c899d57f239c40ffb33da0b7323880be08.  

Also did the same for the parts of the epidermis in commit https://github.com/Planteome/plant-ontology/commit/54a63d798e920fe1446cc8cc87290cf0769c0a28:
PO:0000349 plant epidermal initial cell
PO:0000349 plant epidermal initial cell

These updates will be available in our dev browser tomorrow and will be included in the next full release.

One question: there are approximately 60 child terms of plant epidermis- do you think these all should also have 'plant' added to their names? Many are quite plant specific (for example: root epidermis)

**Comment by cmungall** [comment]
Thanks!

I don't think there is a need for relabeling the descendants. All of these appear to have labels that would not be confused with a non-plant structure; e.g.

PO:0000041 ! epidermal cork cell
PO:0000047 ! leaf lamina epidermis
PO:0000049 ! leaf lamina abaxial epidermis
PO:0000050 ! leaf lamina adaxial epidermis
PO:0000051 ! petiole epidermis
PO:0000112 ! shoot axis epidermis
PO:0000207 ! nectary epidermis
PO:0004013 ! epidermal cell
PO:0005013 ! hypocotyl epidermis
PO:0005023 ! plant ovary outer epidermis
PO:0005024 ! plant ovary inner epidermis
PO:0005679 ! epidermis
PO:0006016 ! leaf epidermis
PO:0006018 ! leaf adaxial epidermis
PO:0006019 ! leaf abaxial epidermis
PO:0006035 ! shoot system epidermis
PO:0006036 ! root epidermis
PO:0006039 ! shoot-borne root epidermis
PO:0006040 ! sepal epidermis
PO:0006041 ! petal epidermis
PO:0006043 ! integument epidermis
PO:0006044 ! inner integument epidermis
PO:0006045 ! outer integument epidermis
PO:0006048 ! seed coat epidermis
PO:0006049 ! scutellum epidermis
PO:0006052 ! petal abaxial epidermis
PO:0006053 ! petal adaxial epidermis
PO:0006054 ! sepal abaxial epidermis
PO:0006055 ! sepal adaxial epidermis
PO:0006056 ! cotyledon epidermis
PO:0006057 ! cotyledon abaxial epidermis
PO:0006058 ! cotyledon adaxial epidermis
PO:0006060 ! filament epidermis
PO:0006061 ! stigma epidermis
PO:0006062 ! style epidermis
PO:0006063 ! plant ovary epidermis
PO:0008006 ! nucellar epidermis
PO:0008027 ! petiole adaxial epidermis
PO:0008029 ! petiole abaxial epidermis
PO:0025046 ! shoot axis tuber epidermis
PO:0025047 ! aerial tuber epidermis
PO:0025048 ! subterranean tuber epidermis
PO:0025096 ! carpel epidermis
PO:0025097 ! stamen epidermis
PO:0025135 ! cigar leaf lamina abaxial epidermis
PO:0025152 ! peduncle epidermis
PO:0025157 ! phyllome epidermis
PO:0025158 ! bract epidermis
PO:0025159 ! bract abaxial epidermis
PO:0025160 ! bract adaxial epidermis
PO:0025178 ! stem epidermis
PO:0025179 ! branch epidermis
PO:0025184 ! tepal epidermis
PO:0025192 ! tepal abaxial epidermis
PO:0025193 ! tepal adaxial epidermis
PO:0025249 ! leaf sheath epidermis
PO:0025250 ! leaf sheath abaxial epidermis
PO:0025251 ! leaf sheath adaxial epidermis
PO:0025617 ! carpel abaxial epidermis
PO:0025618 ! carpel adaxial epidermis
PO:0000263 ! non-hair root epidermal cell
PO:0000332 ! epidermal pavement cell
PO:0000349 ! epidermal initial cell
PO:0025164 ! root epidermal cell
PO:0025165 ! shoot epidermal cell
PO:0025499 ! sepal epidermis giant cell
PO:0030068 ! epidermal rhizoid initial cell

**Comment by cooperl09** [comment]
Agreed

**Comment by cooperl09** [comment]
Updated names and definitions where needed.
