### ISSUE TITLE
Obsolete terms in PO Glossary

### ISSUE THREAD

**Issue by cooperl09** [Planteome/plant-ontology#720]
It would be good if we could adjust the settings so that the obsolete terms do not appear in the PO glossary.
https://planteome.org/po_glossary
It would make it easier for the user and less cluttered- see example:
![image](https://github.com/Planteome/plant-ontology/assets/7378000/eca5df24-b75c-44c4-847d-14994b375f65)

Also, the glossary is not displaying the term names correctly where the word 'OBSOLETE' (all upper case) has been added to the terms name, as required.
For example:
[Term]
id: PO:0000028
name: OBSOLETE pollen tube tip
namespace: plant_anatomy
def: "OBSOLETE. Tip portion of the pollen tube that is rapidly growing." [TAIR_curator:Katica_Ilic]
![image](https://github.com/Planteome/plant-ontology/assets/7378000/599012f1-1b40-4d8d-b1c2-273185d8d5b0)

**Comment by elserj** [comment]
Closed with commit f537c1b
