### ISSUE TITLE
A question about PO ID system

### ISSUE THREAD

**Issue by WordlessMeteor** [Planteome/plant-ontology#727]
Hello! I'm new to Plant Ontology database, and while checking the definition of PO terms, I'm wondering how the ID system is built. To be more specific, the accession number of "plant embryo proper" is PO:0000001, so what do the seven digits represent, respectively? Thank you.

**Comment by cooperl09** [comment]
The seven digit accession numbers, which are preceded by a 2 or 3 letter code are created during curation of the term into the ontology.  They are unique identifiers, sort of like a social security number and form part of a universal resource identifier (URI) for each term.  They are never reused, so if the term is deprecated, the PO:ID is retired.  This is standard practice in the ontology community.  You can compare with the ones used by the Gene Ontology.

**Comment by WordlessMeteor** [comment]
Thank you! So are the 7 digits organized in some specific manner, like first one or two digits represent something, and the next one or two represent something? Otherwise, is the number part for the PO accession number determined by the date that the term was curated?
