### ISSUE TITLE
fruit

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#76]
Currently has no is_a parent. Is part_of infructescence.

Suggest making fruit an is_a child of plant organ.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/76](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/76)

**Comment by cooperl09** [comment]
Proposed revisions to fruit (PO:0009001): New child terms for fruit types

At the Oct. 11, 2016 conference call, we decided to add the various the fruit types to the PO as separate terms.  This will improve the coordination between Plant Ontology and the Trait Ontology.
[http://wiki.planteome.org/index.php/Oct_11th,_2016_Ontology_Working_Group_Meeting](http://wiki.planteome.org/index.php/Oct_11th,_2016_Ontology_Working_Group_Meeting)

The fruit types that are currently listed as synonyms will be added as stand alone terms in the PO.
The main categories of fruits will be (see the associated trackers for each):
* berry
* drupe
* legume
* silique
* follicle
* capsule
* achene
* nut
* samara
* caryopsis
* schizocarp

Thanks so much to @btsinn and @DarioJCavaliere for all the hard work on this!

**Comment by cooperl09** [comment]
Also proposing a slight modification of the definition and comment to accommodate this change:

**Current Def’n**: A multi-tissue plant structure (PO:0025496) which develops from a gynoecium (PO:0009062) and may have as parts one or more seeds (PO:0009010).

**Current Comment:**
A fruit may contain additional plant structures (PO:0009011) that were part of a flower (PO:0009046) and mature along with the gynoecium, such as a receptacle (PO:0009064). A fruit may develop without fertilization in cases of parthenocarpy, apomixis, or other hormone-induced conditions and may not always contain seeds. Fruits only occur in angiosperms.


**Proposed Def’n Revision:** A multi-tissue plant structure (PO:0025496) which develops from a gynoecium (PO:0009062), or a single carpel (PO:0009030), and may have as parts one or more seeds (PO:0009010).

Proposed Comment Revision: A fruit may contain additional plant structures (PO:0009011) that were part of a flower (PO:0009046) and mature along with the gynoecium, such as a receptacle (PO:0009064). A fruit may develop without fertilization in cases of parthenocarpy, apomixis, or other hormone-induced conditions and may not always contain seeds.  When annotating to fruit (PO:0009001) that are referred to as ‘aggregate’, ‘multiple’, or ‘compound’, please annotate directly to the appropriate plant structure, such as receptacle, hypanthium (PO:0009065) or  infructescence (PO:0006342). Fruits only occur in angiosperms.

**Comment by btsinn** [comment]
#642
