### ISSUE TITLE
inflorescence flower pedicel (PO:0009052)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#89]
Current definition of pedicel: [PO:0009052](http://purl.obolibrary.org/obo/PO_0009052): Basal part of the ultimate branch of the inflorescence. [source: APWeb:Glossary].
pedicel currently is_a stalk (https://sourceforge.net/tracker/?func=detail&aid=2972224&group\_id=76834&atid=835555\), which, since stalk is a cardinal organ part, makes pedicel a cardinal organ part.

I suggest that pedicel should NOT be a child of stalk, since it does not fit the definition (A cardinal organ part that is elongated and sub-cylindrical to cylindrical and supports another cardinal organ part), because it supports other organs, not other cardinal organ parts. 

Perhaps pedicel should be a stem, which is an organ.

Reported by: rlwalls2008

Original Ticket: [obo/plant-ontology-po-term-requests/89](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/89)

**Comment by btsinn** [comment]
flower pedicel (PO:0009052) definition and comment revision (moved from issue #668):

Current def'n: An inflorescence branch (PO:0009081) that supports an individual flower (PO:0009046) in an inflorescence (PO:0009049).

Revised def'n: A higher order inflorescence axis (PO:0009081) that terminates in a flower (PO:0009046).

Current comment: The bracteoles are borne on the pedicel, which terminates in a flower. A pedicel is the ultimate branch in an inflorescence.

Revised comment: The pedicel is the ultimate axis in an inflorescence and terminates in a flower.

Synonyms: pedicelo (Spanish, exact), 小花柄 (Japanese, exact)

**Comment by btsinn** [comment]
Renaming of flower pedicel (PO:0009052) to inflorescence pedicel (PO:0009052) to reflect that this term is only used for pedicels of inflorescences.

----------------------------------------------------------------------

inflorescence pedicel (PO:0009052)

Renaming of: _flower pedicel (PO:0009052)_

Previous def'n: 
_An inflorescence branch (PO:0009081) that supports an individual flower (PO:0009046) in an inflorescence (PO:0009049)._

Revised def'n: 
_A pedicel (PO:0030112) that terminates in a flower (PO:0009046) in an inflorescence (PO:0009049)._

Previous comment: 
_The bracteoles are borne on the pedicel, which terminates in a flower. A pedicel is the ultimate branch in an inflorescence._

Revised comment: 
_An inflorescence pedicel is the ultimate axis in an inflorescence._

Previous synonyms: 
_pedicelo (Spanish, exact), 小花柄 (Japanese, exact)_

Revised synonyms: 
_pedicelo (Spanish, broad), 小花柄 (Japanese, related)_

** part_of inflorescence

**Comment by btsinn** [comment]
Revised def'n: 
A pedicel (PO:0030112) that bears a flower (PO:0009046) in an inflorescence (PO:0009049).
