### ISSUE TITLE
stem

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-ontology#96]
Current Definition:
The axial system of plants that bears leaves and buds.n [source: APWeb:Glossary]     Synonyms: cane, culm, stalk, trunk

Comments: It is usually above ground and more or less negatively geotropic, is exogenous in origin, often indeterminate in growth and with secondary thickening.

Problem: Stem has no is_a parent- should be a collective plant structure? OR If we make it a child of plant organ, then penduncle, pedicel and gynophore can be stalks 

Reported by: cooperl09

Original Ticket: [obo/plant-ontology-po-term-requests/96](https://sourceforge.net/p/obo/plant-ontology-po-term-requests/96)

**Comment by cooperl09** [comment]
On reviewing this comment, I am not sure why we said the stem is "exogenous in origin".

Comment: "Often bears leaves and buds. It is usually above ground, more or less negatively geotropic, and exogenous in origin."
Propose revision: A stem often bears leaves and buds. It is usually above ground, and is more or less negatively geotropic.
